\ir ./yeluke/user.sql
\ir ./yeluke/meeting.sql
\ir ./yeluke/engagement.sql
\ir ./yeluke/team.sql
\ir ./yeluke/quiz.sql
\ir ./yeluke/quiz_submission.sql
\ir ./yeluke/quiz_question.sql
\ir ./yeluke/quiz_question_option.sql
\ir ./yeluke/quiz_answer.sql
\ir ./yeluke/ui_element.sql
\ir ./yeluke/assignment.sql
\ir ./yeluke/assignment_field.sql