-- Deployed inside a transaction Zapadka opens and commits.
-- Do not write BEGIN, COMMIT, ROLLBACK, or SAVEPOINT here.
-- Data grants for consuming apps, step 1 of 3: the permission as data
-- (issue #384, ADR 0005).
--
-- An app that consumes course data -- the voting app that lists every
-- submitted URL for one assignment, say -- has had no credential of its own.
-- It ran on a faculty token, which reads everything faculty reads. This
-- records instead exactly what such an app may see: which assignments, which
-- identity attributes of the submitter, which fields. The credential that
-- presents a grant, and the reader that honours it, arrive in the next two
-- migrations; this one is the storage and its lifecycle.
--
-- Two rules shape everything below. A grant is immutable once created: to
-- change what an app may see, revoke the grant and create another, so the
-- record of what each credential could ever read is never rewritten. And every
-- foreign key is restrictive: a field a grant names cannot be renamed or
-- dropped while the grant row exists, revoked or not, because the grant would
-- otherwise silently stop meaning what it meant.
-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------
CREATE TABLE data.api_grant (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (char_length(name) BETWEEN 3 AND 80),
    created_by int NOT NULL REFERENCES data."user" (id),
    created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
    expires_at timestamp with time zone NOT NULL,
    revoked_by int REFERENCES data."user" (id),
    revoked_at timestamp with time zone,
    CONSTRAINT api_grant_expires_after_creation CHECK (expires_at > created_at),
    CONSTRAINT api_grant_max_lifetime CHECK (
    -- The cap personal access tokens carry (01a04817-bound-api-token-lifetime).
    expires_at <= (created_at + '180 days'::interval)),
    CONSTRAINT api_grant_revocation_names_actor_and_time CHECK ((revoked_at IS NULL) = (revoked_by IS NULL)),
    CONSTRAINT api_grant_revoked_after_creation CHECK (revoked_at >= created_at)
)
;
-- tests/db/foreign-key-indexes.sql requires an index led by every referencing
-- column.
CREATE INDEX api_grant_created_by_idx
ON data.api_grant USING btree (created_by)
; CREATE INDEX api_grant_revoked_by_idx
ON data.api_grant USING btree (revoked_by)
; ALTER TABLE data.api_grant
    OWNER TO yelukerest_migrator
; COMMENT ON TABLE data.api_grant IS 'A permission for a consuming app to read granted fields of granted assignments. Immutable after creation except for one revocation. The credential is never stored.'
;
-- One row per granted assignment, carrying the identity attributes the
-- consumer may see for that assignment's submitters. Any subset of the four,
-- possibly none: a leaderboard needs nicknames, a URL lister needs nothing.
CREATE TABLE data.api_grant_assignment (
    grant_id int NOT NULL REFERENCES data.api_grant (id),
    assignment_slug text NOT NULL REFERENCES data.assignment (slug),
    identity text[] NOT NULL CHECK (
    -- `<@` also refuses a NULL element, which is never a subset of anything.
    identity <@ ARRAY['netid', 'name', 'nickname', 'team_nickname']::text[]),
    PRIMARY KEY (grant_id, assignment_slug)
)
; CREATE INDEX api_grant_assignment_assignment_slug_idx
ON data.api_grant_assignment USING btree (assignment_slug)
; ALTER TABLE data.api_grant_assignment
    OWNER TO yelukerest_migrator
; COMMENT ON TABLE data.api_grant_assignment IS 'An assignment a grant covers, with the submitter identity attributes the consumer may see. Fixed at creation.'
;
-- One row per granted field. The key to data.assignment_field is composite
-- because a field slug such as `url` recurs across assignments (ADR 0005): a
-- grant names a field OF an assignment, never a slug that matches everywhere.
CREATE TABLE data.api_grant_assignment_field (
    grant_id int NOT NULL,
    assignment_slug text NOT NULL,
    field_slug text NOT NULL,
    PRIMARY KEY (grant_id, assignment_slug, field_slug),
    FOREIGN KEY (grant_id, assignment_slug) REFERENCES data.api_grant_assignment (grant_id, assignment_slug),
    FOREIGN KEY (field_slug, assignment_slug) REFERENCES data.assignment_field (slug, assignment_slug)
)
; CREATE INDEX api_grant_assignment_field_field_idx
ON data.api_grant_assignment_field USING btree (field_slug, assignment_slug)
; ALTER TABLE data.api_grant_assignment_field
    OWNER TO yelukerest_migrator
; COMMENT ON TABLE data.api_grant_assignment_field IS 'A field of a granted assignment whose submitted body the consumer may read. Fixed at creation; the referenced field cannot be renamed or dropped while this row exists.'
;
-- ---------------------------------------------------------------------------
-- Immutability
-- ---------------------------------------------------------------------------
-- Permission rows are written by data.create_api_grant_rows and by nothing
-- else. The function opens the window by naming the grant it is building in a
-- transaction-local setting; an insert for any other grant, and every update
-- or delete, is refused. This is a guard against a later migration or an
-- admin session writing permissions by hand, not a privilege boundary: the
-- only roles that can reach these tables at all are the migrator and, read
-- only, `api`.
CREATE FUNCTION data.api_grant_permissions_are_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path TO pg_catalog, pg_temp AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF current_setting('yeluke.api_grant_in_creation', true) = NEW.grant_id::text THEN
            RETURN NEW;
        END IF;
    END IF;
    RAISE EXCEPTION 'api grant permissions are fixed at creation; revoke the grant and create another'
        USING ERRCODE = '42501';
END;
$$
; ALTER FUNCTION data.api_grant_permissions_are_immutable() OWNER TO yelukerest_migrator
; CREATE TRIGGER tg_api_grant_assignment_immutable BEFORE INSERT OR DELETE OR UPDATE ON data.api_grant_assignment FOR EACH ROW EXECUTE FUNCTION data.api_grant_permissions_are_immutable()
; CREATE TRIGGER tg_api_grant_assignment_field_immutable BEFORE INSERT OR DELETE OR UPDATE ON data.api_grant_assignment_field FOR EACH ROW EXECUTE FUNCTION data.api_grant_permissions_are_immutable()
;
-- The grant row itself changes exactly once, when it is revoked, and then only
-- in the two revocation columns. Deleting a grant needs no trigger: every grant
-- has at least one permission row, and the restrictive foreign keys refuse to
-- orphan it.
CREATE FUNCTION data.api_grant_allows_only_first_revocation() RETURNS trigger LANGUAGE plpgsql SET search_path TO pg_catalog, pg_temp AS $$
BEGIN
    IF OLD.revoked_at IS NULL
       AND NEW.revoked_at IS NOT NULL
       AND NEW.revoked_by IS NOT NULL
       AND NEW.id = OLD.id
       AND NEW.name = OLD.name
       AND NEW.created_by = OLD.created_by
       AND NEW.created_at = OLD.created_at
       AND NEW.expires_at = OLD.expires_at THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'an api grant changes only by being revoked, once; revoke it and create another'
        USING ERRCODE = '42501';
END;
$$
; ALTER FUNCTION data.api_grant_allows_only_first_revocation() OWNER TO yelukerest_migrator
; CREATE TRIGGER tg_api_grant_first_revocation_only BEFORE UPDATE ON data.api_grant FOR EACH ROW EXECUTE FUNCTION data.api_grant_allows_only_first_revocation()
;
-- ---------------------------------------------------------------------------
-- Creation: the validated insert
-- ---------------------------------------------------------------------------
-- p_assignments is [{"assignment_slug": ..., "identity": [...], "field_slugs":
-- [...]}, ...]. Every rule is checked here and any failure raises, so the
-- caller's transaction gets all the rows or none. Not exposed through the API:
-- step 2 wraps it in api.create_api_grant, which must also sign and return the
-- credential in the same transaction.
CREATE FUNCTION data.create_api_grant_rows(p_name text, p_assignments jsonb, p_expires_at timestamp with time zone, p_created_by int) RETURNS int LANGUAGE plpgsql SET search_path TO pg_catalog, data, pg_temp AS $$
DECLARE
    identity_names CONSTANT text[] := ARRAY['netid', 'name', 'nickname', 'team_nickname'];
    max_lifetime CONSTANT interval := interval '180 days';
    new_id int;
    entry jsonb;
    entry_slug text;
    entry_identity text[];
    entry_fields text[];
    offending text[];
BEGIN
    IF p_name IS NULL OR char_length(p_name) NOT BETWEEN 3 AND 80 THEN
        RAISE EXCEPTION 'a grant name of 3 to 80 characters is required' USING ERRCODE = '22023';
    END IF;
    IF p_expires_at IS NULL OR p_expires_at <= current_timestamp THEN
        RAISE EXCEPTION 'expires_at must be in the future' USING ERRCODE = '22023';
    END IF;
    IF p_expires_at > current_timestamp + max_lifetime THEN
        RAISE EXCEPTION 'expires_at may be at most % from now (% requested, latest allowed is %)',
            max_lifetime, p_expires_at, current_timestamp + max_lifetime
            USING ERRCODE = '22023';
    END IF;
    IF p_created_by IS NULL THEN
        RAISE EXCEPTION 'a creating user is required' USING ERRCODE = '22023';
    END IF;
    IF p_assignments IS NULL OR jsonb_typeof(p_assignments) <> 'array' OR jsonb_array_length(p_assignments) = 0 THEN
        RAISE EXCEPTION 'p_assignments must be a non-empty array of {assignment_slug, identity, field_slugs}'
            USING ERRCODE = '22023';
    END IF;
    IF (SELECT count(*) <> count(DISTINCT e ->> 'assignment_slug') FROM jsonb_array_elements(p_assignments) e) THEN
        RAISE EXCEPTION 'each assignment may appear once in p_assignments' USING ERRCODE = '22023';
    END IF;

    INSERT INTO data.api_grant (name, created_by, expires_at)
    VALUES (p_name, p_created_by, p_expires_at)
    RETURNING data.api_grant.id INTO new_id;

    -- Open the one window in which permission rows may be written (see
    -- data.api_grant_permissions_are_immutable). Transaction-local, so a
    -- failure below discards it with everything else.
    PERFORM set_config('yeluke.api_grant_in_creation', new_id::text, true);

    FOR entry IN SELECT e FROM jsonb_array_elements(p_assignments) e LOOP
        IF jsonb_typeof(entry) <> 'object' THEN
            RAISE EXCEPTION 'each p_assignments entry must be an object' USING ERRCODE = '22023';
        END IF;
        SELECT array_agg(k ORDER BY k) INTO offending
        FROM jsonb_object_keys(entry) k
        WHERE k NOT IN ('assignment_slug', 'identity', 'field_slugs');
        IF offending IS NOT NULL THEN
            RAISE EXCEPTION 'unknown key(s) in p_assignments entry: %', array_to_string(offending, ', ')
                USING ERRCODE = '22023';
        END IF;
        IF jsonb_typeof(entry -> 'assignment_slug') IS DISTINCT FROM 'string' THEN
            RAISE EXCEPTION 'assignment_slug must be a string' USING ERRCODE = '22023';
        END IF;
        entry_slug := entry ->> 'assignment_slug';
        IF NOT EXISTS (SELECT 1 FROM data.assignment a WHERE a.slug = entry_slug) THEN
            RAISE EXCEPTION 'unknown assignment %', entry_slug USING ERRCODE = '22023';
        END IF;

        -- Both lists must be arrays of strings: a JSON null or number is
        -- refused rather than cast. Then no duplicates, then the vocabulary.
        IF jsonb_typeof(entry -> 'identity') IS DISTINCT FROM 'array'
           OR EXISTS (SELECT 1 FROM jsonb_array_elements(entry -> 'identity') i WHERE jsonb_typeof(i) <> 'string') THEN
            RAISE EXCEPTION 'identity for % must be an array of strings', entry_slug USING ERRCODE = '22023';
        END IF;
        SELECT coalesce(array_agg(i), '{}') INTO entry_identity FROM jsonb_array_elements_text(entry -> 'identity') i;
        IF cardinality(entry_identity) <> (SELECT count(DISTINCT i) FROM unnest(entry_identity) i) THEN
            RAISE EXCEPTION 'identity for % lists an attribute twice', entry_slug USING ERRCODE = '22023';
        END IF;
        IF NOT (entry_identity <@ identity_names) THEN
            RAISE EXCEPTION 'identity for % may only name %', entry_slug, array_to_string(identity_names, ', ')
                USING ERRCODE = '22023';
        END IF;

        IF jsonb_typeof(entry -> 'field_slugs') IS DISTINCT FROM 'array'
           OR EXISTS (SELECT 1 FROM jsonb_array_elements(entry -> 'field_slugs') f WHERE jsonb_typeof(f) <> 'string') THEN
            RAISE EXCEPTION 'field_slugs for % must be an array of strings', entry_slug USING ERRCODE = '22023';
        END IF;
        SELECT coalesce(array_agg(f), '{}') INTO entry_fields FROM jsonb_array_elements_text(entry -> 'field_slugs') f;
        IF cardinality(entry_fields) = 0 THEN
            RAISE EXCEPTION 'at least one field of % must be granted', entry_slug USING ERRCODE = '22023';
        END IF;
        IF cardinality(entry_fields) <> (SELECT count(DISTINCT f) FROM unnest(entry_fields) f) THEN
            RAISE EXCEPTION 'field_slugs for % lists a field twice', entry_slug USING ERRCODE = '22023';
        END IF;
        SELECT array_agg(f ORDER BY f) INTO offending
        FROM unnest(entry_fields) f
        WHERE NOT EXISTS (
            SELECT 1 FROM data.assignment_field af
            WHERE af.assignment_slug = entry_slug AND af.slug = f
        );
        IF offending IS NOT NULL THEN
            RAISE EXCEPTION 'unknown field(s) of %: %', entry_slug, array_to_string(offending, ', ')
                USING ERRCODE = '22023';
        END IF;

        INSERT INTO data.api_grant_assignment (grant_id, assignment_slug, identity)
        VALUES (new_id, entry_slug, entry_identity);
        INSERT INTO data.api_grant_assignment_field (grant_id, assignment_slug, field_slug)
        SELECT new_id, entry_slug, f FROM unnest(entry_fields) f;
    END LOOP;

    PERFORM set_config('yeluke.api_grant_in_creation', '', true);
    RETURN new_id;
END;
$$
; ALTER FUNCTION data.create_api_grant_rows(text, jsonb, timestamp with time zone, int) OWNER TO yelukerest_migrator
; REVOKE ALL ON FUNCTION data.create_api_grant_rows(text, jsonb, timestamp with time zone, int) FROM public
; COMMENT ON FUNCTION data.create_api_grant_rows(text, jsonb, timestamp with time zone, int) IS 'Validated, all-or-nothing insert of a grant and its permission rows. Returns the grant id. Called by api.create_api_grant; not an API surface.'
;
-- ---------------------------------------------------------------------------
-- Revoking a grant
-- ---------------------------------------------------------------------------
-- Faculty only, and one-way. A second revoke changes nothing and reports the
-- first actor and time: revocation is a fact about when access ended.
-- The caller is resolved to a current faculty row rather than trusted from the
-- claim alone, so revoked_by always names a real person.
CREATE FUNCTION api.revoke_api_grant(p_id int) RETURNS TABLE (id int, name text, revoked_at timestamp with time zone, revoked_by int) SECURITY DEFINER LANGUAGE plpgsql SET search_path TO pg_catalog, api, data, request, pg_temp AS $$
DECLARE
    caller_id int;
BEGIN
    IF request.user_role() IS DISTINCT FROM 'faculty' THEN
        RAISE insufficient_privilege USING MESSAGE = 'only faculty may revoke an api grant';
    END IF;
    SELECT u.id INTO caller_id FROM data."user" u WHERE u.id = request.user_id() AND u.role = 'faculty';
    IF caller_id IS NULL THEN
        RAISE insufficient_privilege USING MESSAGE = 'the caller is not a current faculty member';
    END IF;

    UPDATE data.api_grant g
       SET revoked_at = current_timestamp, revoked_by = caller_id
     WHERE g.id = p_id AND g.revoked_at IS NULL;

    RETURN QUERY
    SELECT g.id, g.name, g.revoked_at, g.revoked_by
    FROM data.api_grant g
    WHERE g.id = p_id;
END;
$$
; ALTER FUNCTION api.revoke_api_grant(int) OWNER TO yelukerest_migrator
; REVOKE ALL ON FUNCTION api.revoke_api_grant(int) FROM public
; GRANT execute ON FUNCTION api.revoke_api_grant(int) TO faculty
; COMMENT ON FUNCTION api.revoke_api_grant(int) IS 'Revoke an api grant. Faculty only; one-way; a second call leaves the first actor and time in place. Returns no row for an unknown id.'
;
-- ---------------------------------------------------------------------------
-- API view -- faculty only, and never a credential
-- ---------------------------------------------------------------------------
-- `permissions` has the shape api.create_api_grant accepts, so what faculty
-- see is what was asked for.
CREATE VIEW api.api_grants WITH (security_barrier=true) AS
    SELECT
        g.id, g.name, g.created_by, g.created_at, g.expires_at, g.revoked_by,
        g.revoked_at, g.revoked_at IS NULL
        AND g.expires_at > current_timestamp AS is_active,
        (
            SELECT
                jsonb_agg(jsonb_build_object('assignment_slug', ga.assignment_slug, 'identity', to_jsonb(ga.identity), 'field_slugs', (
                    SELECT jsonb_agg(f.field_slug ORDER BY f.field_slug)
                    FROM data.api_grant_assignment_field f
                    WHERE
                        f.grant_id = ga.grant_id
                        AND f.assignment_slug = ga.assignment_slug
                )) ORDER BY ga.assignment_slug)
            FROM data.api_grant_assignment ga
            WHERE ga.grant_id = g.id
        ) AS permissions
    FROM data.api_grant g
    WHERE request.user_role() = 'faculty'::text
; ALTER VIEW api.api_grants
    OWNER TO api
; COMMENT ON VIEW api.api_grants IS 'Grants issued to consuming apps, with their permissions and lifecycle. Faculty only. Never exposes a credential; none is stored.'
; COMMENT ON COLUMN api.api_grants.id IS 'Grant identifier; the grant_id claim of its credential'
; COMMENT ON COLUMN api.api_grants.name IS 'Human-supplied label naming the consuming app'
; COMMENT ON COLUMN api.api_grants.created_by IS 'Faculty user who created the grant'
; COMMENT ON COLUMN api.api_grants.created_at IS 'When the grant was created'
; COMMENT ON COLUMN api.api_grants.expires_at IS 'When the grant, and its credential, stop being honoured'
; COMMENT ON COLUMN api.api_grants.revoked_by IS 'Faculty user who revoked the grant, if it was'
; COMMENT ON COLUMN api.api_grants.revoked_at IS 'When the grant was revoked, if it was'
; COMMENT ON COLUMN api.api_grants.is_active IS 'True when the grant is neither revoked nor expired'
; COMMENT ON COLUMN api.api_grants.permissions IS 'Array of {assignment_slug, identity, field_slugs}: what the credential may read. Fixed at creation.'
; GRANT select ON data.api_grant, data.api_grant_assignment, data.api_grant_assignment_field TO api
; GRANT select ON api.api_grants TO faculty
; NOTIFY pgrst, 'reload schema'
