begin;
select plan(3);

SELECT set_eq(
    $$
        SELECT n.nspname || '.' || c.relname || '.' || a.attname
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE a.attidentity = 'd'
        AND (n.nspname, c.relname, a.attname) IN (
            ('data', 'artifact', 'id'),
            ('data', 'assignment_grade_exception', 'id'),
            ('data', 'assignment_submission', 'id'),
            ('data', 'quiz', 'id'),
            ('data', 'quiz_grade_exception', 'id'),
            ('data', 'user', 'id'),
            ('data', 'user_secret', 'id')
        )
    $$,
    ARRAY[
        'data.artifact.id',
        'data.assignment_grade_exception.id',
        'data.assignment_submission.id',
        'data.quiz.id',
        'data.quiz_grade_exception.id',
        'data.user.id',
        'data.user_secret.id'
    ],
    'surrogate id columns should be generated by default identity columns'
);

SELECT is_empty(
    $$
        SELECT n.nspname || '.' || c.relname || '.' || a.attname
        FROM pg_attrdef d
        JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
        JOIN pg_class c ON c.oid = d.adrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'data'
        AND pg_get_expr(d.adbin, d.adrelid) LIKE 'nextval(%'
    $$,
    'data schema should not use serial-style nextval column defaults'
);

SELECT is_empty(
    $$
        SELECT r.rolname || ':' || s.relname
        FROM pg_roles r
        CROSS JOIN pg_class s
        JOIN pg_namespace n ON n.oid = s.relnamespace
        WHERE r.rolname IN ('faculty', 'student', 'ta')
        AND n.nspname = 'data'
        AND s.relname IN ('assignment_submission_id_seq', 'quiz_id_seq')
        AND has_sequence_privilege(r.oid, s.oid, 'USAGE')
    $$,
    'inserting through api views should not require direct sequence usage grants'
);

select * from finish();
rollback;
