-- data.assignment_repository_snapshot: what the graded artifact actually was at
-- each student's effective deadline (#22).
--
-- Sample data this file leans on: users 1 (abc123, student, team bright-fog),
-- 2 (bde456, student, team hazy-mountain), 3 (klj39, faculty), 4 (jlb325, ta,
-- no team); assignments exam-1 and team-selection (individual, published),
-- js-koans (individual, draft) and project-update-1 (team, published); and the
-- shipped exception giving team hazy-mountain until 3019 on project-update-1.
--
-- Every assignment in the sample data closes in 3018, so nothing is ever due.
-- The deadlines below are moved into the past deliberately, and `current_timestamp`
-- is fixed for the whole of this transaction, so a timestamp written here and the
-- one the view computes are the same value rather than merely close.
--
-- Repository ids are given explicitly. The column is GENERATED BY DEFAULT, and a
-- known id is what lets the assertions name a repository instead of chasing a
-- sequence.

SELECT plan(57);

-- ---------------------------------------------------------------------------
-- Shape and privileges
-- ---------------------------------------------------------------------------

SELECT has_table(
    'data', 'assignment_repository_snapshot',
    'assignment_repository_snapshot table should record deadline captures'
);

SELECT view_owner_is(
    'api', 'assignment_repository_snapshots', 'api',
    'api.assignment_repository_snapshots should be owned by the api role, or its RLS policy never applies'
);

SELECT view_owner_is(
    'api', 'assignment_repository_snapshots_due', 'api',
    'api.assignment_repository_snapshots_due should be owned by the api role, or its RLS policy never applies'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'faculty',
    ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
    'faculty should have CRUD on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'student', ARRAY['SELECT'],
    'student should only be granted SELECT on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'ta', ARRAY['SELECT'],
    'ta should only be granted SELECT on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'anonymous', ARRAY[]::text[],
    'anonymous should be granted nothing on view "api.assignment_repository_snapshots"'
);

-- The queue carries every student's effective deadline and is read by the
-- snapshot runner alone.
SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'faculty', ARRAY['SELECT'],
    'faculty should be able to read the snapshot queue'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'student', ARRAY[]::text[],
    'student should be granted nothing on the snapshot queue'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'ta', ARRAY[]::text[],
    'ta should be granted nothing on the snapshot queue'
);

SELECT table_privs_are(
    'data', 'assignment_repository_snapshot', 'student', ARRAY[]::text[],
    'student should be granted nothing on "data.assignment_repository_snapshot"'
);

SELECT table_privs_are(
    'data', 'assignment_repository_snapshot', 'faculty', ARRAY[]::text[],
    'faculty should be granted nothing on "data.assignment_repository_snapshot"'
);

-- ---------------------------------------------------------------------------
-- The board
-- ---------------------------------------------------------------------------
-- exam-1, js-koans and project-update-1 all closed a day ago. team-selection
-- still closes in 3018. js-koans stays a draft, which is the point of it being
-- here.

UPDATE data.assignment
SET closed_at = current_timestamp - interval '1 day'
WHERE slug IN ('exam-1', 'js-koans', 'project-update-1');

INSERT INTO data.assignment_repository
    (id, assignment_slug, is_team, user_id, provider_repo_id, provider_full_name)
VALUES
    (9001, 'exam-1', FALSE, 1, 300000001, 'mgt-656/exam-1-abc123'),
    (9002, 'exam-1', FALSE, 2, 300000002, 'mgt-656/exam-1-bde456'),
    (9005, 'js-koans', FALSE, 1, 300000005, 'mgt-656/js-koans-abc123'),
    (9006, 'team-selection', FALSE, 1, 300000006, 'mgt-656/team-selection-abc123');

INSERT INTO data.assignment_repository
    (id, assignment_slug, is_team, team_nickname, provider_repo_id, provider_full_name)
VALUES
    (9003, 'project-update-1', TRUE, 'bright-fog', 300000003, 'mgt-656/project-update-1-bright-fog'),
    (9004, 'project-update-1', TRUE, 'hazy-mountain', 300000004, 'mgt-656/project-update-1-hazy-mountain');

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------
-- Written against the base table as the test superuser, because these are
-- constraints rather than policy: they hold whoever is asking.

SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (id, assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (8001, 9001,
            current_timestamp - interval '1 day',
            current_timestamp - interval '23 hours',
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            's3://mgt-656-snapshots/exam-1/abc123.bundle',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    'a verified capture records a commit, a bundle uri and a digest'
);

-- The failure path is the reason this table has rows at all: a capture that
-- did not work must leave evidence, because a missing row is indistinguishable
-- from "not due yet".
SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at, error)
        VALUES (9002,
            current_timestamp - interval '1 day',
            current_timestamp - interval '23 hours',
            'clone failed: repository not found')
    $$,
    'a failed capture is a row, carrying the error and no artifact'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp, FALSE)
    $$,
    '23514',
    NULL,
    'an unverified capture cannot omit why it failed'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_sha256, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'a verified capture cannot omit the bundle it claims to have stored'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified, error)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE, 'but also it failed')
    $$,
    '23514',
    NULL,
    'a verified capture cannot also carry an error'
);

-- git is midway through the SHA-1 to SHA-256 migration, so both lengths are
-- real. Neither may arrive uppercase, or one commit becomes two strings.
SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9003,
            current_timestamp - interval '1 day',
            current_timestamp - interval '1 hour',
            'aa11bb22cc33dd44ee55ff6677889900aa11bb22cc33dd44ee55ff6677889900',
            's3://mgt-656-snapshots/project-update-1/bright-fog.bundle',
            'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210',
            TRUE)
    $$,
    'a sha256 object-format repository records a 64 character commit'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1C5A0B2E4F6D8A0C2E4F6D8A0C2E4F6D8A0C2E4F',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'an uppercase commit sha is refused, so one commit cannot be two strings'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'an abbreviated commit sha is refused'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789ABCDEF0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'an uppercase bundle digest is refused, so a comparison cannot fail on case'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9002, current_timestamp - interval '1 day', current_timestamp,
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'a truncated bundle digest is refused'
);

-- The central invariant: a capture cannot precede the deadline it claims to
-- capture, or "this is what existed at the deadline" is not a statement about
-- the deadline at all.
SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9002,
            current_timestamp - interval '1 day',
            current_timestamp - interval '2 days',
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            's3://mgt-656-snapshots/exam-1/bde456.bundle',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            TRUE)
    $$,
    '23514',
    NULL,
    'a capture cannot have been taken before the deadline it claims to capture'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at, error)
        VALUES (999999, current_timestamp - interval '1 day', current_timestamp, 'nope')
    $$,
    '23503',
    NULL,
    'a snapshot cannot name a repository that does not exist'
);

-- The mapping is what makes a snapshot mean anything, so it cannot be deleted
-- out from under one.
SELECT throws_ok(
    $$ DELETE FROM data.assignment_repository WHERE id = 9001 $$,
    '23503',
    NULL,
    'a repository that has been snapshotted cannot be deleted'
);

-- ---------------------------------------------------------------------------
-- One current snapshot per repository, and failures that pile up freely
-- ---------------------------------------------------------------------------

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9001,
            current_timestamp - interval '1 day',
            current_timestamp - interval '1 hour',
            'bb22cc33dd44ee55ff6677889900aa11bb22cc33',
            's3://mgt-656-snapshots/exam-1/abc123-again.bundle',
            'aaaabbbbccccddddeeeeffff00001111aaaabbbbccccddddeeeeffff00001111',
            TRUE)
    $$,
    '23505',
    NULL,
    'a repository cannot have two current verified snapshots at once'
);

SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, captured_at, error)
        VALUES
            (9002, current_timestamp - interval '1 day', current_timestamp, 'clone failed again'),
            (9002, current_timestamp - interval '1 day', current_timestamp, 'and again')
    $$,
    'failed captures accumulate: the first failure does not block recording the next'
);

-- Supersession, not deletion. Retiring the old row is what makes room for the
-- new one, and the old row stays.
SELECT lives_ok(
    $$
        UPDATE data.assignment_repository_snapshot
        SET superseded_at = current_timestamp
        WHERE id = 8001
    $$,
    'a current snapshot can be superseded'
);

-- The generic updated_at trigger, exercised rather than merely declared: a row
-- that has been retired must not keep claiming it was last touched when it was
-- captured. `current_timestamp` is fixed for this transaction, so what proves
-- the trigger ran is that updated_at has moved past created_at at all.
SELECT ok(
    (
        SELECT updated_at > created_at
        FROM data.assignment_repository_snapshot
        WHERE id = 8001
    ),
    'tg_assignment_repository_snapshot_update_timestamps refreshes updated_at'
);

SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (id, assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (8002, 9001,
            current_timestamp - interval '1 day',
            current_timestamp - interval '1 hour',
            'bb22cc33dd44ee55ff6677889900aa11bb22cc33',
            's3://mgt-656-snapshots/exam-1/abc123-again.bundle',
            'aaaabbbbccccddddeeeeffff00001111aaaabbbbccccddddeeeeffff00001111',
            TRUE)
    $$,
    'a newer capture becomes current once the old one has been superseded'
);

SELECT results_eq(
    $$
        SELECT id, superseded_at IS NULL AS is_current
        FROM data.assignment_repository_snapshot
        WHERE assignment_repository_id = 9001
        ORDER BY id
    $$,
    $$ VALUES (8001, FALSE), (8002, TRUE) $$,
    'the superseded snapshot is kept rather than deleted: the audit trail is the point'
);

SELECT throws_ok(
    $$
        UPDATE data.assignment_repository_snapshot
        SET superseded_at = current_timestamp - interval '2 days'
        WHERE id = 8002
    $$,
    '23514',
    NULL,
    'a snapshot cannot have been superseded before it was captured'
);

-- ---------------------------------------------------------------------------
-- What is due for a snapshot
-- ---------------------------------------------------------------------------
-- The queue is faculty-only, so it is read as faculty throughout.

SET LOCAL ROLE faculty;
SET request.jwt.claim.role = 'faculty';
SET request.jwt.claim.user_id = '3';

-- 9001 and 9003 each hold a current verified snapshot, so neither is due. 9002
-- has only failures, so it still is. 9004's team holds an exception running to
-- 3019. 9005 is a draft. 9006 does not close until 3018.
SELECT set_eq(
    'SELECT assignment_repository_id FROM api.assignment_repository_snapshots_due',
    ARRAY[9002],
    'due is: deadline passed, and no current verified snapshot for that deadline'
);

SELECT results_eq(
    $$
        SELECT failed_attempt_count, last_failed_at = current_timestamp AS failed_just_now
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9002
    $$,
    $$ VALUES (3, TRUE) $$,
    'the queue counts failed attempts at this deadline, so retrying forever can be a choice rather than the only behavior'
);

-- 9004's assignment closed a day ago, but its team holds an exception running
-- to 3019. An effective deadline that fell back to the assignment's would put
-- it on the queue, and the team would be graded on work it was told it still
-- had a thousand years to do.
SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9004
    $$,
    'a team holding an extension is not judged against the assignment deadline'
);

RESET ROLE;

UPDATE data.assignment_grade_exception
SET closed_at = current_timestamp - interval '2 days'
WHERE assignment_slug = 'project-update-1' AND team_nickname = 'hazy-mountain';

SET LOCAL ROLE faculty;

SELECT results_eq(
    $$
        SELECT effective_closed_at = current_timestamp - interval '2 days' AS uses_the_exception,
               assignment_closed_at = current_timestamp - interval '1 day' AS reports_the_assignment_deadline
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9004
    $$,
    $$ VALUES (TRUE, TRUE) $$,
    'the effective deadline is the exception''s closed_at, and the assignment''s own is reported beside it'
);

-- A draft assignment is not visible to students through api.assignments and is
-- still being written, so its closed_at is not a deadline anyone worked against.
SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9005
    $$,
    'a draft assignment is never due for a snapshot, however long ago its closed_at was'
);

SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9006
    $$,
    'an assignment whose deadline has not passed is not due'
);

-- ---------------------------------------------------------------------------
-- An extension granted after a capture
-- ---------------------------------------------------------------------------
-- This is the case that decides the whole design. 9001 was captured at the
-- assignment deadline. User 1 then gets an extension on exam-1.

RESET ROLE;

INSERT INTO data.assignment_grade_exception (assignment_slug, is_team, user_id, closed_at)
VALUES ('exam-1', FALSE, 1, current_timestamp + interval '1 day');

SET LOCAL ROLE faculty;

SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9001
    $$,
    'while an extension is still running the repository is not due, and the snapshot already taken stays current'
);

SELECT results_eq(
    $$
        SELECT count(*)::int
        FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9001
        AND is_verified AND superseded_at IS NULL
    $$,
    $$ VALUES (1) $$,
    'a window with no current snapshot at all would be worse, so the old capture is not retired early'
);

RESET ROLE;

UPDATE data.assignment_grade_exception
SET closed_at = current_timestamp - interval '1 hour'
WHERE assignment_slug = 'exam-1' AND user_id = 1;

SET LOCAL ROLE faculty;

SELECT results_eq(
    $$
        SELECT effective_closed_at = current_timestamp - interval '1 hour' AS uses_the_extension,
               failed_attempt_count
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9001
    $$,
    $$ VALUES (TRUE, 0) $$,
    'once the extended deadline passes the repository is due again, because the snapshot it has is for the earlier deadline'
);

-- And the way out of the queue is a capture recorded against the *new*
-- deadline. A row carrying the old effective_closed_at would leave the
-- repository due forever.
RESET ROLE;

UPDATE data.assignment_repository_snapshot
SET superseded_at = current_timestamp
WHERE id = 8002;

INSERT INTO data.assignment_repository_snapshot
    (assignment_repository_id, effective_closed_at, captured_at,
     commit_sha, bundle_uri, bundle_sha256, is_verified)
VALUES (9001,
    current_timestamp - interval '1 hour',
    current_timestamp,
    'cc33dd44ee55ff6677889900aa11bb22cc33dd44',
    's3://mgt-656-snapshots/exam-1/abc123-extended.bundle',
    'bbbbccccddddeeeeffff00001111222233334444bbbbccccddddeeeeffff0000',
    TRUE);

SET LOCAL ROLE faculty;

SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9001
    $$,
    'a capture recorded against the extended deadline takes the repository off the queue'
);

SELECT results_eq(
    $$
        SELECT count(*)::int
        FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9001
    $$,
    $$ VALUES (3) $$,
    'and all three captures survive, superseded rather than deleted'
);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

SELECT results_eq(
    $$
        SELECT assignment_repository_id, count(*)::int
        FROM api.assignment_repository_snapshots
        GROUP BY assignment_repository_id
        ORDER BY assignment_repository_id
    $$,
    $$ VALUES (9001, 3), (9002, 3), (9003, 1) $$,
    'faculty should see every capture, including the failures'
);

SELECT lives_ok(
    $$
        INSERT INTO api.assignment_repository_snapshots
            (assignment_repository_id, effective_closed_at, captured_at, error)
        VALUES (9004, current_timestamp - interval '2 days', current_timestamp,
            'bundle upload rejected by the store')
    $$,
    'faculty should be able to record a capture through the view'
);

SET LOCAL ROLE student;
SET request.jwt.claim.role = 'student';
SET request.jwt.claim.user_id = '1';

-- User 1 owns 9001 and is on team bright-fog, which owns 9003.
SELECT set_eq(
    'SELECT DISTINCT assignment_repository_id FROM api.assignment_repository_snapshots',
    ARRAY[9001, 9003],
    'a student should see the captures of their own repositories and their current team''s'
);

SELECT is_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id IN (9002, 9004)
    $$,
    'a student should not see which commit another student or another team handed in'
);

SELECT throws_ok(
    $$ SELECT assignment_repository_id FROM api.assignment_repository_snapshots_due $$,
    '42501',
    NULL,
    'a student cannot read the snapshot queue'
);

SELECT throws_ok(
    $$
        INSERT INTO api.assignment_repository_snapshots
            (assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri, bundle_sha256, is_verified)
        VALUES (9001, current_timestamp - interval '1 hour', current_timestamp,
            'dd44ee55ff6677889900aa11bb22cc33dd44ee55',
            's3://mine/better.bundle',
            'ccccddddeeeeffff00001111222233334444555566667777888899990000aaaa',
            TRUE)
    $$,
    '42501',
    NULL,
    'a student cannot nominate a different artifact as the one that was graded'
);

SELECT throws_ok(
    $$
        UPDATE api.assignment_repository_snapshots
        SET commit_sha = 'dd44ee55ff6677889900aa11bb22cc33dd44ee55'
        WHERE assignment_repository_id = 9001
    $$,
    '42501',
    NULL,
    'a student cannot rewrite the commit their own snapshot records'
);

SELECT throws_ok(
    $$
        DELETE FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9001
    $$,
    '42501',
    NULL,
    'a student cannot delete the record of what was graded'
);

SET request.jwt.claim.user_id = '2';

SELECT set_eq(
    'SELECT DISTINCT assignment_repository_id FROM api.assignment_repository_snapshots',
    ARRAY[9002, 9004],
    'the other student sees their own captures, and the first student''s are not among them'
);

-- A TA is on the student side of the policy, not the faculty side.
SET LOCAL ROLE ta;
SET request.jwt.claim.role = 'ta';
SET request.jwt.claim.user_id = '4';

SELECT is_empty(
    'SELECT id FROM api.assignment_repository_snapshots',
    'a ta with no repositories of their own should see no captures'
);

SELECT throws_ok(
    $$ SELECT assignment_repository_id FROM api.assignment_repository_snapshots_due $$,
    '42501',
    NULL,
    'a ta cannot read the snapshot queue'
);

SET LOCAL ROLE anonymous;
SET request.jwt.claim.role = 'anonymous';

SELECT throws_ok(
    $$ SELECT id FROM api.assignment_repository_snapshots $$,
    '42501',
    NULL,
    'an anonymous request cannot read captures at all'
);

RESET ROLE;

-- Ownership is resolved live through data.assignment_repository, so a roster
-- change moves which team's captures a student can see -- the same rule the
-- repository itself follows, because a repository is a grant on the forge.
UPDATE data."user" SET team_nickname = 'hazy-mountain' WHERE id = 1;

SET LOCAL ROLE student;
SET request.jwt.claim.role = 'student';
SET request.jwt.claim.user_id = '1';

SELECT is_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9003
    $$,
    'a student moved off a team stops seeing that team''s captures'
);

SELECT isnt_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9004
    $$,
    'and starts seeing the captures of the team they joined'
);

RESET ROLE;

SELECT * FROM finish();
