-- data.assignment_repository_snapshot: what each student's repository contained
-- at their effective deadline (#22).
--
-- Sample data this file leans on: users 1 (abc123, student, team bright-fog),
-- 2 (bde456, student, team hazy-mountain), 3 (klj39, faculty), 4 (jlb325, ta,
-- no team); assignments exam-1 and team-selection (individual, published),
-- js-koans (individual, draft) and project-update-1 (team, published); and the
-- shipped exception giving team hazy-mountain until 3019 on project-update-1.
--
-- Every assignment in the sample data closes in 3018, so nothing is ever due.
-- The deadlines below are moved into the past deliberately, and `current_timestamp`
-- is fixed for the whole of this transaction, so a timestamp written here and the
-- one the view computes are the same value rather than merely close.
--
-- Repository and snapshot ids are given explicitly. The columns are GENERATED BY
-- DEFAULT, and a known id is what lets the assertions name a row instead of
-- chasing a sequence.

SELECT plan(39);

-- ---------------------------------------------------------------------------
-- Shape and privileges
-- ---------------------------------------------------------------------------

SELECT has_table(
    'data', 'assignment_repository_snapshot',
    'assignment_repository_snapshot table should record deadline captures'
);

SELECT view_owner_is(
    'api', 'assignment_repository_snapshots', 'api',
    'api.assignment_repository_snapshots should be owned by the api role, or its RLS policy never applies'
);

SELECT view_owner_is(
    'api', 'assignment_repository_snapshots_due', 'api',
    'api.assignment_repository_snapshots_due should be owned by the api role, or its RLS policy never applies'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'faculty',
    ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
    'faculty should have CRUD on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'student', ARRAY['SELECT'],
    'student should only be granted SELECT on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'ta', ARRAY['SELECT'],
    'ta should only be granted SELECT on view "api.assignment_repository_snapshots"'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots', 'anonymous', ARRAY[]::text[],
    'anonymous should be granted nothing on view "api.assignment_repository_snapshots"'
);

-- The queue carries every student's effective deadline and is read by the
-- snapshot runner alone.
SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'faculty', ARRAY['SELECT'],
    'faculty should be able to read the snapshot queue'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'student', ARRAY[]::text[],
    'student should be granted nothing on the snapshot queue'
);

SELECT table_privs_are(
    'api', 'assignment_repository_snapshots_due', 'ta', ARRAY[]::text[],
    'ta should be granted nothing on the snapshot queue'
);

SELECT table_privs_are(
    'data', 'assignment_repository_snapshot', 'student', ARRAY[]::text[],
    'student should be granted nothing on "data.assignment_repository_snapshot"'
);

-- ---------------------------------------------------------------------------
-- Fixtures
-- ---------------------------------------------------------------------------

UPDATE data.assignment
SET closed_at = current_timestamp - interval '1 day'
WHERE slug IN ('exam-1', 'js-koans', 'project-update-1');

INSERT INTO data.assignment_repository
    (id, assignment_slug, is_team, user_id, provider_repo_id, provider_full_name)
VALUES
    (9001, 'exam-1', FALSE, 1, 300000001, 'mgt-656/exam-1-abc123'),
    (9002, 'exam-1', FALSE, 2, 300000002, 'mgt-656/exam-1-bde456'),
    (9005, 'js-koans', FALSE, 1, 300000005, 'mgt-656/js-koans-abc123'),
    (9006, 'team-selection', FALSE, 1, 300000006, 'mgt-656/team-selection-abc123');

INSERT INTO data.assignment_repository
    (id, assignment_slug, is_team, team_nickname, provider_repo_id, provider_full_name)
VALUES
    (9003, 'project-update-1', TRUE, 'bright-fog', 300000003, 'mgt-656/project-update-1-bright-fog'),
    (9004, 'project-update-1', TRUE, 'hazy-mountain', 300000004, 'mgt-656/project-update-1-hazy-mountain');

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------
-- Written against the base table as the test superuser, because these are
-- constraints rather than policy: they hold whoever is asking.

SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (id, assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri)
        VALUES (8001, 9001,
            current_timestamp - interval '1 day',
            current_timestamp - interval '23 hours',
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f',
            'file:///srv/snapshots/exam-1/9001.bundle')
    $$,
    'a capture records the commit that was graded and where its bundle went'
);

-- git is midway through the SHA-1 to SHA-256 migration, so both lengths are
-- real.
SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (id, assignment_repository_id, effective_closed_at, captured_at,
             commit_sha, bundle_uri)
        VALUES (8003, 9003,
            current_timestamp - interval '1 day',
            current_timestamp - interval '23 hours',
            '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
            'file:///srv/snapshots/project-update-1/9003.bundle')
    $$,
    'a sha-256 object name is a commit too'
);

-- Uppercase would make one commit into two strings.
SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9002, current_timestamp - interval '1 day',
            '1C5A0B2E4F6D8A0C2E4F6D8A0C2E4F6D8A0C2E4F',
            'file:///srv/snapshots/exam-1/9002.bundle')
    $$,
    '23514',
    NULL,
    'a commit sha may not arrive uppercase'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9002, current_timestamp - interval '1 day',
            'HEAD',
            'file:///srv/snapshots/exam-1/9002.bundle')
    $$,
    '23514',
    NULL,
    'a ref name is not a commit sha'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9002, current_timestamp - interval '1 day',
            '1c5a0b2e4f6d8a0c2e4f6d8a0c2e4f6d8a0c2e4f', '')
    $$,
    '23514',
    NULL,
    'a capture cannot claim a bundle at no location'
);

-- One capture per repository per deadline. This is what makes "which artifact
-- was graded" resolve to a single row without anybody having to retire another.
SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9001, current_timestamp - interval '1 day',
            'bb22cc33dd44ee55ff6677889900aa11bb22cc33',
            'file:///srv/snapshots/exam-1/9001-again.bundle')
    $$,
    '23505',
    NULL,
    'a repository cannot hold two snapshots for one deadline'
);

-- A different deadline is a different row, and the old one stays. That is how
-- an extension is recorded: nothing is superseded, nothing is deleted.
SELECT lives_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (id, assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (8002, 9001, current_timestamp - interval '2 days',
            'bb22cc33dd44ee55ff6677889900aa11bb22cc33',
            'file:///srv/snapshots/exam-1/9001-earlier.bundle')
    $$,
    'a capture for a different deadline sits alongside the first rather than replacing it'
);

SELECT throws_ok(
    $$
        INSERT INTO data.assignment_repository_snapshot
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (99999, current_timestamp - interval '1 day',
            'bb22cc33dd44ee55ff6677889900aa11bb22cc33',
            'file:///srv/snapshots/nowhere.bundle')
    $$,
    '23503',
    NULL,
    'a snapshot cannot name a repository that does not exist'
);

-- ---------------------------------------------------------------------------
-- What is due for a snapshot
-- ---------------------------------------------------------------------------
-- The queue is faculty-only, so it is read as faculty throughout.

SET LOCAL ROLE faculty;
SET request.jwt.claim.role = 'faculty';
SET request.jwt.claim.user_id = '3';

-- 9001 and 9003 hold a snapshot for the deadline in force, so neither is due.
-- 9002 holds none. 9004's team has an exception running to 3019. 9005 is a
-- draft. 9006 does not close until 3018.
SELECT set_eq(
    'SELECT assignment_repository_id FROM api.assignment_repository_snapshots_due',
    ARRAY[9002],
    'due is: deadline passed, and no snapshot for that deadline'
);

SELECT results_eq(
    $$
        SELECT effective_closed_at = current_timestamp - interval '1 day'
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9002
    $$,
    $$ VALUES (TRUE) $$,
    'with no exception in play the effective deadline is the assignment''s own'
);

-- 9004's assignment closed a day ago, but its team holds an exception running
-- to 3019. An effective deadline that fell back to the assignment's would grade
-- the team on work it was told it still had a thousand years to do.
SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9004
    $$,
    'a team holding an extension is not judged against the assignment deadline'
);

-- A draft is not visible to students and is still being written, so its
-- closed_at is not a deadline anyone is working against.
SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9005
    $$,
    'a draft assignment is never due for capture'
);

RESET ROLE;

-- Bring the team's extension into the past, but an hour ago rather than the
-- assignment's day ago: the exception is the later of the two, so it governs.
UPDATE data.assignment_grade_exception
SET closed_at = current_timestamp - interval '1 hour'
WHERE assignment_slug = 'project-update-1' AND team_nickname = 'hazy-mountain';

SET LOCAL ROLE faculty;

SELECT results_eq(
    $$
        SELECT effective_closed_at = current_timestamp - interval '1 hour'
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9004
    $$,
    $$ VALUES (TRUE) $$,
    'an exception later than the assignment deadline is the one that governs'
);

RESET ROLE;

-- Capture 9002 at the deadline in force, then extend that student. The
-- extension gives the repository a new effective deadline that nothing covers,
-- so it becomes due again on its own -- no reconciliation step, nothing to
-- remember to re-run. This is the failure Classroom has and the reason the
-- queue matches on the deadline rather than merely on the repository.
INSERT INTO data.assignment_repository_snapshot
    (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
VALUES (9002, current_timestamp - interval '1 day',
    'cc33dd44ee55ff6677889900aa11bb22cc33dd44',
    'file:///srv/snapshots/exam-1/9002.bundle');

SET LOCAL ROLE faculty;

SELECT is_empty(
    $$
        SELECT assignment_repository_id
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9002
    $$,
    'a repository captured at its deadline drops off the queue'
);

RESET ROLE;

INSERT INTO data.assignment_grade_exception (assignment_slug, is_team, user_id, closed_at)
VALUES ('exam-1', FALSE, 2, current_timestamp - interval '2 hours');

SET LOCAL ROLE faculty;

SELECT results_eq(
    $$
        SELECT effective_closed_at = current_timestamp - interval '2 hours'
        FROM api.assignment_repository_snapshots_due
        WHERE assignment_repository_id = 9002
    $$,
    $$ VALUES (TRUE) $$,
    'an extension granted after a capture makes the repository due again, at the new deadline'
);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

SET request.jwt.claim.role = 'faculty';
SET request.jwt.claim.user_id = '3';

SELECT results_eq(
    $$
        SELECT assignment_repository_id, count(*)::int
        FROM api.assignment_repository_snapshots
        GROUP BY assignment_repository_id
        ORDER BY assignment_repository_id
    $$,
    $$ VALUES (9001, 2), (9002, 1), (9003, 1) $$,
    'faculty should see every capture'
);

SELECT lives_ok(
    $$
        INSERT INTO api.assignment_repository_snapshots
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9004, current_timestamp - interval '1 hour',
            'dd44ee55ff6677889900aa11bb22cc33dd44ee55',
            'file:///srv/snapshots/project-update-1/9004.bundle')
    $$,
    'faculty should be able to record a capture through the view'
);

SET LOCAL ROLE student;
SET request.jwt.claim.role = 'student';
SET request.jwt.claim.user_id = '1';

-- User 1 owns 9001 and is on team bright-fog, which owns 9003.
SELECT set_eq(
    'SELECT DISTINCT assignment_repository_id FROM api.assignment_repository_snapshots',
    ARRAY[9001, 9003],
    'a student should see the captures of their own repositories and their current team''s'
);

SELECT is_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id IN (9002, 9004)
    $$,
    'a student should not see which commit another student or another team handed in'
);

SELECT throws_ok(
    $$ SELECT assignment_repository_id FROM api.assignment_repository_snapshots_due $$,
    '42501',
    NULL,
    'a student cannot read the snapshot queue'
);

SELECT throws_ok(
    $$
        INSERT INTO api.assignment_repository_snapshots
            (assignment_repository_id, effective_closed_at, commit_sha, bundle_uri)
        VALUES (9001, current_timestamp - interval '1 hour',
            'dd44ee55ff6677889900aa11bb22cc33dd44ee55',
            'file:///srv/snapshots/mine/better.bundle')
    $$,
    '42501',
    NULL,
    'a student cannot nominate a different artifact as the one that was graded'
);

SELECT throws_ok(
    $$
        UPDATE api.assignment_repository_snapshots
        SET commit_sha = 'dd44ee55ff6677889900aa11bb22cc33dd44ee55'
        WHERE assignment_repository_id = 9001
    $$,
    '42501',
    NULL,
    'a student cannot rewrite the commit their own snapshot records'
);

SELECT throws_ok(
    $$
        DELETE FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9001
    $$,
    '42501',
    NULL,
    'a student cannot delete the record of what was graded'
);

SET request.jwt.claim.user_id = '2';

SELECT set_eq(
    'SELECT DISTINCT assignment_repository_id FROM api.assignment_repository_snapshots',
    ARRAY[9002, 9004],
    'the other student sees their own captures, and the first student''s are not among them'
);

-- A TA is on the student side of the policy, not the faculty side.
SET LOCAL ROLE ta;
SET request.jwt.claim.role = 'ta';
SET request.jwt.claim.user_id = '4';

SELECT is_empty(
    'SELECT id FROM api.assignment_repository_snapshots',
    'a ta with no repositories of their own should see no captures'
);

SET LOCAL ROLE anonymous;
SET request.jwt.claim.role = 'anonymous';

SELECT throws_ok(
    $$ SELECT id FROM api.assignment_repository_snapshots $$,
    '42501',
    NULL,
    'an anonymous request cannot read captures at all'
);

RESET ROLE;

-- Ownership is resolved live through data.assignment_repository, so a roster
-- change moves which team's captures a student can see -- the same rule the
-- repository itself follows, because a repository is a grant on the forge.
UPDATE data."user" SET team_nickname = 'hazy-mountain' WHERE id = 1;

SET LOCAL ROLE student;
SET request.jwt.claim.role = 'student';
SET request.jwt.claim.user_id = '1';

SELECT is_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9003
    $$,
    'a student moved off a team stops seeing that team''s captures'
);

SELECT isnt_empty(
    $$
        SELECT id FROM api.assignment_repository_snapshots
        WHERE assignment_repository_id = 9004
    $$,
    'and starts seeing the captures of the team they joined'
);

RESET ROLE;

SELECT * FROM finish();
