volumes:
    # A named volume to share data between containers
    elmclient-build:
        external: false
    caddy_data:
    caddy_config:
services:
    elmclient:
        build:
            context: elmclient
            target: app
        # Set the location where docker will put our files
        working_dir: /opt/app
        environment:
            - DEVELOPMENT=${DEVELOPMENT}
            - PIAZZA_URL=${ELMCLIENT_PIAZZA_URL}
            - ABOUT_URL=${ELMCLIENT_ABOUT_URL}
            - CANVAS_URL=${ELMCLIENT_CANVAS_URL}
            - SLACK_URL=${ELMCLIENT_SLACK_URL}
            - COURSE_TITLE=${ELMCLIENT_COURSE_TITLE}
        volumes:
            - elmclient-build:/opt/app/dist
            - './elmclient/src:/opt/app/src'
            - './elmclient/tests:/opt/app/tests'
            - './elmclient/run.sh:/opt/app/run.sh'
            - './elmclient/build.sh:/opt/app/build.sh'
        entrypoint: '/opt/app/run.sh'

    elmclient-test:
        profiles:
            - test
        build:
            context: elmclient
            target: test
        working_dir: /opt/app
        volumes:
            - './elmclient/src:/opt/app/src'
            - './elmclient/tests:/opt/app/tests'
            - './elmclient/elm.json:/opt/app/elm.json'
        entrypoint:
            - elm-test-rs
            - --deno

    # PostgREST instance, is responsible for communicating with the database
    # and providing a REST api, (almost) every request that is sent to the database goes through it
    postgrest:
        image: ${POSTGREST_IMAGE:-ghcr.io/kljensen/docker-postgrest-static:14.14}
        ports:
            - '127.0.0.1:3000:${POSTGREST_PORT}'
        environment:
            - PGRST_DB_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
            - PGRST_DB_SCHEMAS=${DB_SCHEMA}
            - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
            - PGRST_DB_POOL=${DB_POOL}
            - PGRST_JWT_SECRET=${JWT_SECRET}
            - PGRST_DB_MAX_ROWS=${MAX_ROWS}
            - PGRST_DB_PRE_REQUEST=${PRE_REQUEST:-api.check_request_jwt}
            - PGRST_OPENAPI_SERVER_PROXY_URI=${SERVER_PROXY_URI}
            - PGRST_LOG_LEVEL=${PGRST_LOG_LEVEL:-error}

    # Caddy instance that sits in front of PostgREST.
    # All the requests coming into the system are first hitting this component.
    # After some processing/checks and transformation, the request is forwarded
    # to PostgREST down the stack.
    caddy:
        build: caddy
        ports:
            - '${CADDY_LISTEN_HOST}:80:80'
            - '${CADDY_LISTEN_HOST}:443:443'
            - '${CADDY_LISTEN_HOST}:443:443/udp'
        restart: on-failure
        environment:
            - FQDN=${FQDN}
            - CADDY_ENV=${CADDY_ENV:-production}
            - NAKED_FQDN=${NAKED_FQDN}
            - POSTGREST_PORT=${POSTGREST_PORT}
            - AUTHAPP_PORT=${AUTHAPP_PORT}
            - AWS_ACCESS_KEY_ID=${CADDY_ACME_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${CADDY_ACME_SECRET_ACCESS_KEY}
            - AWS_REGION=${CADDY_ACME_AWS_REGION}

        volumes:
            - elmclient-build:/var/elmclient/
            - './caddy/Caddyfile:/etc/caddy/Caddyfile'
            - './caddy/development.caddyfile:/etc/caddy/development.caddyfile'
            - './caddy/production.caddyfile:/etc/caddy/production.caddyfile'
            - './caddy/html:/usr/share/caddy/html'
            - './caddy/user_code:/usr/share/caddy/user_code'
            - caddy_data:/data
            - caddy_config:/config

    authapp:
        build: authapp
        ports:
            - '127.0.0.1:${AUTHAPP_HOST_PORT}:${AUTHAPP_PORT}'
        environment:
            - DEVELOPMENT=${DEVELOPMENT}
            - PORT=${AUTHAPP_PORT}
            - CAS_URI=${AUTHAPP_CAS_URI}
            - CAS_VALIDATION_URI=${AUTHAPP_CAS_VALIDATION_URI}
            - POSTGREST_HOST=${POSTGREST_HOST}
            - POSTGREST_PORT=${POSTGREST_PORT}
            - AUTHAPP_JWT=${AUTHAPP_JWT}
