\ir meeting.sql
\ir engagement.sql
\ir team.sql
\ir quiz.sql
\ir quiz_submission.sql
\ir quiz_question.sql
\ir quiz_question_option.sql
\ir quiz_answer.sql
\ir ui_element.sql
\ir assignment.sql
\ir assignment_field.sql
\ir assignment_submission.sql
\ir assignment_field_submission.sql
\ir quiz_grade.sql
\ir assignment_grade.sql
\ir assignment_grade_exception.sql
\ir quiz_grade_exception.sql
\ir user_secret.sql
