
-- This file is generated by the DataFiller free software.
-- This software comes without any warranty whatsoever.
-- Use at your own risk. Beware, this script may destroy your data!
-- License is GPLv3, see http://www.gnu.org/copyleft/gpl.html
-- Get latest version from http://www.coelho.net/datafiller.html

-- Data generated by: /usr/local/bin/datafiller
-- Version 2.0.1-dev (r832 on 2015-11-01)
-- For postgresql on 2017-12-27T19:55:50.184175 (UTC)
-- 
-- fill table data.meeting (3)
\echo # filling table data.meeting (3)
COPY data.meeting (slug,title,summary,description,begins_at,duration,is_draft,created_at,updated_at) FROM STDIN (ENCODING 'utf-8', FREEZE ON);
intro	Introduction to the class	summary_2_2_2	description_1_	2017-12-27 14:54:50	80 minutes	FALSE	2017-12-27 14:54:50	2017-12-27 14:55:50
structuredquerylang	Databases and Structured Query Language	summary_1_1_1_1_	descripti	2017-12-27 14:54:50	80 minutes	TRUE	2017-12-27 14:55:50	2017-12-27 14:53:50
entrepreneurship-woot	The Lean Start-up	summary_3_	description_1_	2017-12-27 14:55:50	80 minutes	FALSE	2017-12-27 14:53:50	2017-12-27 14:53:50
server-side-apps	Server-side web applications	summary_3_	description_1_	2017-12-27 14:55:50	80 minutes	FALSE	2017-12-27 14:53:50	2017-12-27 14:53:50
\.

UPDATE data.meeting SET description = $thestring$
[View raw (TEST.md)](https://raw.github.com/adamschwartz/github-markdown-kitchen-sink/master/README.md)

This is a paragraph. Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


Header 1
========

Header 2
--------

# Header 1
## Header 2
### Header 3
#### Header 4
##### Header 5
###### Header 6


# Header 1 #
## Header 2 ##
### Header 3 ###
#### Header 4 ####
##### Header 5 #####
###### Header 6 ######

Blockquote:

> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus. Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.

> ## This is a header.
> 1. This is the first list item.
> 2. This is the second list item.
>
> Here's some example code:
>
>     Markdown.generate();

- Red
- Green
- Blue


+ Red
+ Green
+ Blue


* Red
* Green
* Blue


```javascript
var x = 123e5;
var y = 123e-5;
document.getElementById("demo").innerHTML = x + "<br>" + y;

```



1. Buy flour and salt
1. Mix together with water
1. Bake

```markdown
1. Buy flour and salt
1. Mix together with water
1. Bake
```



Paragraph:

    Code

<!-- -->

    Paragraph:

        Code



* * *

***

*****

- - -

---------------------------------------

    * * *

    ***

    *****

    - - -

    ---------------------------------------



This is [an example](http://example.com "Example") link.

[This link](http://example.com) has no title attr.

This is [an example] [id] reference-style link.

[id]: http://example.com "Optional Title"

    This is [an example](http://example.com "Example") link.

    [This link](http://example.com) has no title attr.

    This is [an example] [id] reference-style link.

    [id]: http://example.com "Optional Title"



*single asterisks*

_single underscores_

**double asterisks**

__double underscores__

    *single asterisks*

    _single underscores_

    **double asterisks**

    __double underscores__



This paragraph has some `code` in it.

    This paragraph has some `code` in it.



![Alt Text](http://placehold.it/200x50 "Image Title")

![Alt Text](http://placehold.it/200x50 "Image Title")
$thestring$ WHERE slug='intro';
-- 
-- analyze modified tables
ANALYZE data.meeting;
