truncate data.meeting restart identity cascade;
truncate data.engagement restart identity cascade;
truncate data.team restart identity cascade;
truncate data.quiz restart identity cascade;
truncate data.quiz_question_option restart identity cascade;
truncate data.quiz_question restart identity cascade;
truncate data.quiz_submission restart identity cascade;
truncate data.quiz_answer restart identity cascade;
-- user is truncated elsewhere
