-- What each student's repository contained at their deadline (#22).
--
-- Graders clone the student repository and grade HEAD, so whatever a student
-- pushes after the deadline is what gets graded. So at each student's effective
-- deadline -- the later of assignment.closed_at and any applicable
-- assignment_grade_exception.closed_at, which is exactly what the RLS on
-- data.assignment_submission permits writes until -- record the commit that was
-- HEAD and where the `git bundle` of the repository was written.
--
-- A bundle rather than a tarball because `version-control` is an assignment
-- *about* git history, and a tarball discards it. The commit SHA alongside it
-- because a bundle carries every branch and the grader needs to know which
-- commit was the one.
--
-- Consumer: `admin snapshot-repos` in yale-mgt-656-fall-2026/admin.
--
-- Deployed inside a transaction Zapadka opens and commits.
-- Do not write BEGIN, COMMIT, ROLLBACK, or SAVEPOINT here.

-- ---------------------------------------------------------------------------
-- data.assignment_repository_snapshot
-- ---------------------------------------------------------------------------
CREATE TABLE data.assignment_repository_snapshot (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    assignment_repository_id INT NOT NULL
        REFERENCES data.assignment_repository(id)
        ON UPDATE CASCADE,

    -- The deadline this capture was made for. Stored rather than re-derived, so
    -- a later extension cannot rewrite what this row claims -- and so a
    -- repository whose deadline moves becomes due again on its own, because
    -- nothing covers the new deadline yet.
    effective_closed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    captured_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,

    -- Lowercase hex, SHA-1 or SHA-256, so a repository on SHA-256 object names
    -- needs no migration here.
    commit_sha TEXT NOT NULL
        CHECK (commit_sha ~ '^[0-9a-f]{40}$' OR commit_sha ~ '^[0-9a-f]{64}$'),

    -- Where the bundle is. A location, not a credential: authorization to read
    -- it lives in the store, and presigned URLs do not belong in a table.
    bundle_uri TEXT NOT NULL
        CHECK (char_length(bundle_uri) BETWEEN 1 AND 2048),

    -- One snapshot per repository per deadline.
    --
    -- A failed capture writes nothing at all, so the repository stays due and
    -- the next run retries it: the absence of a row *is* the retry queue. An
    -- extension gives the repository a new effective_closed_at and so a new
    -- row, and the old row stays as history rather than being retired.
    --
    -- This also satisfies tests/db/foreign-key-indexes.sql, which wants an
    -- index led by the referencing column and ignores partial ones.
    CONSTRAINT assignment_repository_snapshot_per_deadline
        UNIQUE (assignment_repository_id, effective_closed_at)
);

COMMENT ON TABLE data.assignment_repository_snapshot IS
    'What each student repository contained at its effective deadline: the commit to grade and where its git bundle was written';

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON data.assignment_repository_snapshot TO api;

ALTER TABLE data.assignment_repository_snapshot ENABLE ROW LEVEL SECURITY;

-- Faculty read and write. A student reads the snapshots of their own repository
-- and nothing else -- the same split data.assignment_repository uses, for the
-- same reason: a student asking "which commit of mine was graded" is the whole
-- support path a regrade dispute runs down, and it should not need a faculty
-- member in the loop. Writing is faculty-only, or a student could nominate a
-- different artifact as the graded one.
--
-- Ownership resolves through data.assignment_repository rather than being
-- copied onto this table, so there stays one definition of who owns a
-- repository, live team membership included.
CREATE POLICY assignment_repository_snapshot_access_policy
    ON data.assignment_repository_snapshot TO api
USING (
    (request.user_role() = 'faculty')
    OR
    (
        request.user_role() = ANY('{student,ta}'::text[])
        AND EXISTS (
            SELECT 1
            FROM data.assignment_repository AS r
            WHERE r.id = assignment_repository_snapshot.assignment_repository_id
            AND (
                (NOT r.is_team AND request.user_id() = r.user_id)
                OR
                (r.is_team AND EXISTS (
                    SELECT 1
                    FROM data."user" AS u
                    WHERE u.id = request.user_id()
                    AND u.team_nickname = r.team_nickname
                ))
            )
        )
    )
) WITH CHECK (
    request.user_role() = 'faculty'
);

-- ---------------------------------------------------------------------------
-- api.assignment_repository_snapshots
-- ---------------------------------------------------------------------------
-- Owned by `api` so the policy above is what governs reads through PostgREST.
CREATE OR REPLACE VIEW api.assignment_repository_snapshots AS
    SELECT * FROM data.assignment_repository_snapshot;

ALTER VIEW api.assignment_repository_snapshots OWNER TO api;

-- tests/db/structure.sql requires a comment on every api view and every one of
-- its columns.
COMMENT ON VIEW api.assignment_repository_snapshots IS
    'Deadline captures of student repositories: which commit was graded, and where its bundle is';
COMMENT ON COLUMN api.assignment_repository_snapshots.id IS
    'Surrogate key for this capture';
COMMENT ON COLUMN api.assignment_repository_snapshots.assignment_repository_id IS
    'The provisioned repository this is a snapshot of';
COMMENT ON COLUMN api.assignment_repository_snapshots.effective_closed_at IS
    'The deadline this capture was made for: the later of the assignment deadline and any grade exception that applied, which is what the student could write until';
COMMENT ON COLUMN api.assignment_repository_snapshots.captured_at IS
    'When the capture was actually observed, which is later than the deadline by however long the runner took to get to it';
COMMENT ON COLUMN api.assignment_repository_snapshots.commit_sha IS
    'The commit to grade, lowercase hex, SHA-1 or SHA-256';
COMMENT ON COLUMN api.assignment_repository_snapshots.bundle_uri IS
    'Where the git bundle was written. A location, not a credential';

-- Read-only for students and TAs; the policy above narrows it to their own rows.
GRANT SELECT ON api.assignment_repository_snapshots TO student, ta;

-- The snapshot runner authenticates as faculty and writes here.
GRANT SELECT, INSERT, UPDATE, DELETE ON api.assignment_repository_snapshots TO faculty;

-- ---------------------------------------------------------------------------
-- api.assignment_repository_snapshots_due
-- ---------------------------------------------------------------------------
-- The work queue: which repositories need capturing right now.
--
-- This exists because the effective-deadline expression must live in one place.
-- Extensions move deadlines individually, so the runner cannot schedule one job
-- at the common deadline -- it polls for work that has *become* due -- and every
-- client that re-derived the deadline would be one more place for it to drift
-- away from the RLS on data.assignment_submission, which is where the
-- definition comes from.
--
-- The matching rule is that RLS's, copied deliberately: an exception applies
-- when it names the same assignment and either its user_id or its team_nickname
-- equals the repository's. NULL is never equal to NULL, so that one predicate
-- gives the individual/team split for free. At most one exception can match --
-- data.assignment_grade_exception's two partial unique indexes make (assignment,
-- user) and (assignment, team) unique -- so the LEFT JOIN cannot fan out.
--
-- The deadline is the *later* of the two, not the exception's. The RLS permits a
-- write when `a.is_open OR (e.closed_at > current_timestamp AND ...)`, and that
-- is an OR: an exception closing earlier than the assignment does not shorten
-- anything, and nothing forbids one. Taking the exception unconditionally would
-- snapshot a repository whose owner is still legitimately writing to it.
--
-- "Due" is three conditions: the assignment is not a draft (a draft is not
-- visible to students and its closed_at is not a deadline anyone is working
-- against); the effective deadline has passed; and there is no snapshot for that
-- same deadline. Matching the third on the deadline rather than merely on the
-- repository is what makes an extension work -- once the new deadline passes,
-- nothing covers it, so the repository becomes due again on its own with no
-- reconciliation step to remember to run.
CREATE OR REPLACE VIEW api.assignment_repository_snapshots_due
WITH (security_barrier = true) AS
    SELECT
        r.id AS assignment_repository_id,
        r.assignment_slug,
        r.is_team,
        r.user_id,
        r.team_nickname,
        r.provider,
        r.provider_repo_id,
        r.provider_full_name,
        d.effective_closed_at
    FROM data.assignment_repository AS r
    JOIN data.assignment AS a
        ON a.slug = r.assignment_slug
    LEFT JOIN data.assignment_grade_exception AS e
        ON e.assignment_slug = r.assignment_slug
        AND (e.user_id = r.user_id OR e.team_nickname = r.team_nickname)
    -- Naming the expression once, so the places that need it cannot drift.
    -- GREATEST ignores NULLs in PostgreSQL, so the no-exception case needs no
    -- COALESCE around it.
    CROSS JOIN LATERAL (
        SELECT GREATEST(a.closed_at, e.closed_at) AS effective_closed_at
    ) AS d
    WHERE NOT a.is_draft
    AND d.effective_closed_at <= current_timestamp
    AND NOT EXISTS (
        SELECT 1
        FROM data.assignment_repository_snapshot AS s
        WHERE s.assignment_repository_id = r.id
        AND s.effective_closed_at = d.effective_closed_at
    );

ALTER VIEW api.assignment_repository_snapshots_due OWNER TO api;

COMMENT ON VIEW api.assignment_repository_snapshots_due IS
    'Repositories whose effective deadline has passed with no snapshot for that deadline. The snapshot runner''s work queue';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.assignment_repository_id IS
    'The repository to capture, joinable to api.assignment_repositories.id';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.assignment_slug IS
    'The assignment whose deadline has passed';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.is_team IS
    'True when the repository belongs to a team rather than an individual student';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.user_id IS
    'Owning student, set for an individual assignment and NULL otherwise';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.team_nickname IS
    'Owning team, set for a team assignment and NULL otherwise';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider IS
    'Forge hosting the repository, such as github';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider_repo_id IS
    'Forge repository id, which is what the runner should resolve the clone URL from';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider_full_name IS
    'Forge repository name such as org/repo. Display only, and expected to go stale';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.effective_closed_at IS
    'The deadline that governs this repository: the later of the assignment''s closed_at and any applicable grade exception''s, because an exception raises a deadline and never lowers it. Record it on the snapshot exactly as it appears here, or the repository will look due forever';

-- Faculty only. A work queue for the runner, carrying other students' deadlines,
-- that nobody else has any use for.
GRANT SELECT ON api.assignment_repository_snapshots_due TO faculty;

-- ---------------------------------------------------------------------------
-- Compatibility version
-- ---------------------------------------------------------------------------
-- schema_compatibility_version reaches 6: the api schema gains two views, which
-- is a change of shape. admin_api_version stays 9, because no RPC was added --
-- the snapshot runner reads a view and writes a view.
--
-- Additive, so a client that reads neither view works against 5 and 6 alike and
-- declares {5, 6}; the snapshot runner declares {6} alone. Not `>= 6` -- a floor
-- would sail straight through the next shape that removes something, exactly as
-- `>= 3` sailed through version 4. See docs/platform-compatibility.md.
CREATE OR REPLACE VIEW api.platform_version AS
    SELECT
        'yelukerest'::text AS platform,
        1::integer AS platform_compatibility_version,
        6::integer AS schema_compatibility_version,
        9::integer AS admin_api_version;

ALTER VIEW api.platform_version OWNER TO api;

COMMENT ON VIEW api.platform_version IS
    'Single-row compatibility metadata for course admin preflight checks';
COMMENT ON COLUMN api.platform_version.platform IS
    'Platform identifier expected by course admin tooling';
COMMENT ON COLUMN api.platform_version.platform_compatibility_version IS
    'Integer compatibility version for Yelukerest platform behavior';
COMMENT ON COLUMN api.platform_version.schema_compatibility_version IS
    'Integer identifying the api schema shape. Check for membership in the set of shapes the client supports, NOT with >=: a shape can lose columns and views, and version 4 did. A client pinned to >= 3 would pass its own preflight against 4 and then fail on its first request.';
COMMENT ON COLUMN api.platform_version.admin_api_version IS
    'Integer compatibility version for generic admin API operations. Only ever grows -- each bump adds an RPC without removing one -- so >= is the correct check.';

-- ---------------------------------------------------------------------------
-- Tell PostgREST the API changed
-- ---------------------------------------------------------------------------
-- PostgREST answers from a schema cache built at startup and does not
-- rediscover new relations on its own. Without this, api.platform_version starts
-- advertising shape 6 the instant this commits while
-- GET /rest/assignment_repository_snapshots_due still returns 404.
--
-- NOTIFY is transactional: the payload is delivered at commit and discarded on
-- rollback, so this fires when and only when the migration lands.
NOTIFY pgrst, 'reload schema';
