-- What the graded artifact actually was, at each student's deadline (#22).
--
-- Graders clone the student repository and grade HEAD, so nothing stops a push
-- after the deadline from changing what gets graded. The old patch for that was
-- scripts/remove-student-write-to-github.sh, which greps repository names by
-- substring and takes extensions as a hand-passed skip list -- so an extension
-- granted after it runs is simply missed, which is Classroom's own documented
-- bug reproduced.
--
-- Repository lock says "the student cannot change this". What grading needs is
-- "this exact artifact is what was graded", which is stronger, auditable, and
-- survives a force-push, a December regrade, and an assignment whose server has
-- to keep running all semester.
--
-- So at each student's effective deadline -- assignment_grade_exception.closed_at
-- if one applies, else assignment.closed_at, which is exactly the expression the
-- RLS on data.assignment_submission already evaluates -- capture the resolved
-- commit SHA, a durable `git bundle`, and the bundle's SHA-256 digest.
--
-- The SHA alone is not enough. A force-push cannot alter a commit but it can
-- make the commit unreachable, and GitHub does not promise to retain unreachable
-- objects. A tarball is also wrong: `version-control` is an assignment *about*
-- git history and a tarball discards it. The bundle is the artifact; the SHA
-- says which commit inside it to check out; the digest says the bundle is the
-- one that was captured.
--
-- Consumer: the course-side snapshot runner in yale-mgt-656-fall-2026/admin#22.
--
-- Deployed inside a transaction Zapadka opens and commits.
-- Do not write BEGIN, COMMIT, ROLLBACK, or SAVEPOINT here.

-- ---------------------------------------------------------------------------
-- data.assignment_repository_snapshot
-- ---------------------------------------------------------------------------
-- One row per capture *attempt*, not one row per repository.
--
-- Failures are rows, not absences. A capture that could not resolve HEAD, could
-- not push the bundle, or produced a digest that did not match on read-back
-- must leave a row behind saying so. The audit trail is the entire point of
-- this table, and a missing row is indistinguishable from "not due yet" -- which
-- is precisely the state a silently failing runner would be mistaken for, for
-- as long as nobody looked.
CREATE TABLE data.assignment_repository_snapshot (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The repository this is a snapshot of. NO ACTION on delete, deliberately:
    -- a repository record that has been snapshotted cannot be deleted until its
    -- snapshots are, which is the same protection data.assignment_grade gives
    -- data.assignment_submission. Deleting the mapping would strand the
    -- snapshots as rows about nothing, and "we graded commit X of some
    -- repository" is not an audit trail.
    --
    -- ON UPDATE CASCADE is inherited habit rather than need -- the referenced
    -- column is an identity and does not move -- and costs nothing.
    assignment_repository_id INT NOT NULL
        REFERENCES data.assignment_repository(id)
        ON UPDATE CASCADE,

    -- The deadline this capture was made *for*, copied in rather than derived on
    -- read. It has to be stored: the effective deadline is a live computation
    -- over assignment.closed_at and any exception, and both of those move. A
    -- snapshot whose deadline was re-derived at read time would silently start
    -- claiming to be the capture for whatever deadline is current now, which
    -- destroys the one fact the row exists to record.
    --
    -- It is also what makes "is this repository due again" answerable: see
    -- api.assignment_repository_snapshots_due below.
    effective_closed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    -- When the capture was actually observed, which is *not* the deadline. There
    -- is a real window between the two -- the runner polls every few minutes --
    -- and git commit timestamps are user-controlled, so they cannot close it.
    -- Recording the true capture time is the honest option; narrowing the window
    -- is a matter of polling more often, and closing it entirely would need a
    -- short-lived write lock on the forge. Record reality either way.
    captured_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,

    -- A capture cannot precede the deadline it claims to capture. This is the
    -- table's central invariant, and without it a row asserting "this is what
    -- existed at the deadline" could have been taken an hour before it.
    CONSTRAINT captured_after_deadline CHECK (captured_at >= effective_closed_at),

    -- The resolved commit. Forty hex for SHA-1 and sixty-four for SHA-256,
    -- because git is midway through that migration and a repository created with
    -- an object-format of sha256 hands back the longer one. Lowercase only: git
    -- emits lowercase, and accepting both cases would make one commit two
    -- strings.
    --
    -- Nullable, because a failed capture has no commit -- that is what makes it a
    -- failure. The completeness constraint below is what stops a *successful*
    -- one from omitting it.
    commit_sha TEXT
        CHECK (commit_sha ~ '^[0-9a-f]{40}$' OR commit_sha ~ '^[0-9a-f]{64}$'),

    -- Where the bundle lives. Plain text on purpose: S3, a mounted volume, or
    -- somewhere else entirely is an operational choice, and pinning it into the
    -- schema would make moving the store a migration. The issue's preference is
    -- that it be independent of the student repository and ideally outside the
    -- org; nothing here can enforce that, and pretending otherwise with a CHECK
    -- on the hostname would only be a lie with a maintenance cost.
    --
    -- A location, never a credential. A presigned URL does not belong here: it
    -- expires, which makes it useless to a December regrade, and students can
    -- read this column. Authorization to fetch the bundle lives in the store.
    bundle_uri TEXT
        CHECK (char_length(bundle_uri) BETWEEN 1 AND 2048),

    -- SHA-256 of the bundle bytes, so a grader can prove the file they fetched is
    -- the file that was captured. Sixty-four lowercase hex, exactly -- a digest
    -- that is sometimes uppercase and sometimes truncated is a digest nobody
    -- compares.
    bundle_sha256 TEXT
        CHECK (bundle_sha256 ~ '^[0-9a-f]{64}$'),

    -- Whether the capture was verified end to end: the bundle was written, read
    -- back, and its digest recomputed to the value recorded above. This is not
    -- "the runner did not crash". Everything downstream keys on it, so it is the
    -- one flag worth being strict about.
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,

    -- Why it failed, when it failed. Required on failure and forbidden on
    -- success, per the constraint below.
    error TEXT
        CHECK (error IS NULL OR char_length(btrim(error)) BETWEEN 1 AND 8192),

    -- A verified snapshot is complete or it is not verified. An unverified one
    -- says why. Both halves matter: a verified row missing its bundle URI is a
    -- promise the grader cannot cash, and an unverified row with no error is a
    -- failure nobody can act on -- it reads as "something went wrong once".
    CONSTRAINT verified_snapshot_is_complete CHECK (
        (
            is_verified
            AND commit_sha IS NOT NULL
            AND bundle_uri IS NOT NULL
            AND bundle_sha256 IS NOT NULL
            AND error IS NULL
        )
        OR
        (NOT is_verified AND error IS NOT NULL)
    ),

    -- Supersession, not deletion. When an extension moves a deadline later, the
    -- snapshot taken at the old deadline is still a true statement about what
    -- existed then, and deleting it would erase exactly the history a grade
    -- dispute needs. It stops being *current*, which is a different claim, and
    -- this column is where that claim is recorded -- with the time, because "when
    -- did this stop being the artifact we grade" is the question an audit asks.
    superseded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT superseded_after_captured
        CHECK (superseded_at IS NULL OR superseded_at >= captured_at),

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    CONSTRAINT updated_after_created CHECK (updated_at >= created_at)
);

-- "The current snapshot for this repository" resolves to one row or none, and
-- the database is what guarantees it. A grader who has to pick between two
-- candidate artifacts is back where this table started.
--
-- Keyed on the repository alone, not on (repository, deadline): a repository has
-- one artifact that gets graded at a time, and a capture for a new deadline
-- becomes current by superseding the old one rather than by sitting alongside
-- it. Retiring the old row is left to the writer that has just proved it holds a
-- newer one -- the database's job here is to make two current snapshots
-- unrepresentable, not to guess when one should be retired.
--
-- The predicate is narrowed to verified rows so that failures accumulate freely.
-- A repository that fails ten times in a row has ten rows, which is the shape of
-- the evidence; a unique index over all rows would let the first failure block
-- every retry from being recorded.
--
-- Partial-unique is the shape data.assignment_repository already uses for its
-- own per-student and per-team rules, for the same reason: the interesting
-- uniqueness is always conditional.
CREATE UNIQUE INDEX assignment_repository_snapshot_current
    ON data.assignment_repository_snapshot (assignment_repository_id)
    WHERE is_verified AND superseded_at IS NULL;

-- Plain btree covering the foreign key's referencing column, in the
-- constraint's own column order. tests/db/foreign-key-indexes.sql requires this
-- of every foreign key in `data` and ignores any index carrying a predicate --
-- correctly, since a partial index cannot serve a referential integrity check --
-- so the partial unique above does not count.
--
-- `effective_closed_at` is appended rather than given a second index. The test
-- and the referential check both match on a leading-column prefix, and every
-- interesting lookup here -- "is there a snapshot for this repository at this
-- deadline" -- wants both columns anyway.
CREATE INDEX idx_assignment_repository_snapshot_repository_fk
    ON data.assignment_repository_snapshot (assignment_repository_id, effective_closed_at);

-- The generic updated_at trigger, already deployed and already routed through
-- data.touched_at, so this table inherits the #308 fix rather than restating it.
-- No new function.
CREATE TRIGGER tg_assignment_repository_snapshot_update_timestamps
    BEFORE INSERT OR UPDATE
    ON data.assignment_repository_snapshot
    FOR EACH ROW
EXECUTE FUNCTION data.update_updated_at_column();

COMMENT ON TABLE data.assignment_repository_snapshot IS
    'One row per attempt to capture a student repository at its effective deadline: commit SHA, bundle URI, bundle digest, and the outcome';

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON data.assignment_repository_snapshot TO api;

ALTER TABLE data.assignment_repository_snapshot ENABLE ROW LEVEL SECURITY;

-- Faculty read and write. A student reads the snapshots of their own repository
-- and nothing else. Exactly the split data.assignment_repository uses, and
-- exactly the same reasoning: a student needs to be able to ask "which commit of
-- mine was graded" without a faculty member in the loop, which is the whole
-- support path a regrade dispute runs down. Writing is faculty-only, because a
-- student who could write here could nominate a different artifact as the graded
-- one, which is the property the table exists to establish.
--
-- Ownership is resolved through data.assignment_repository rather than
-- duplicated onto this table. That keeps one definition of who owns a
-- repository, including the live-team rule -- a student moved off a team loses
-- the team repository on the forge at the same moment, so live membership is the
-- answer that stays true here too.
CREATE POLICY assignment_repository_snapshot_access_policy
    ON data.assignment_repository_snapshot TO api
USING (
    (request.user_role() = 'faculty')
    OR
    (
        request.user_role() = ANY('{student,ta}'::text[])
        AND EXISTS (
            SELECT 1
            FROM data.assignment_repository AS r
            WHERE r.id = assignment_repository_snapshot.assignment_repository_id
            AND (
                (NOT r.is_team AND request.user_id() = r.user_id)
                OR
                (r.is_team AND EXISTS (
                    SELECT 1
                    FROM data."user" AS u
                    WHERE u.id = request.user_id()
                    AND u.team_nickname = r.team_nickname
                ))
            )
        )
    )
) WITH CHECK (
    request.user_role() = 'faculty'
);

-- ---------------------------------------------------------------------------
-- api.assignment_repository_snapshots
-- ---------------------------------------------------------------------------
-- Owned by `api` so the policy above is what governs reads through PostgREST.
CREATE OR REPLACE VIEW api.assignment_repository_snapshots AS
    SELECT * FROM data.assignment_repository_snapshot;

ALTER VIEW api.assignment_repository_snapshots OWNER TO api;

-- tests/db/structure.sql requires a comment on every api view and every one of
-- its columns.
COMMENT ON VIEW api.assignment_repository_snapshots IS
    'Deadline captures of student repositories: what the graded artifact was, and whether the capture can be trusted';
COMMENT ON COLUMN api.assignment_repository_snapshots.id IS
    'Surrogate key for this capture attempt';
COMMENT ON COLUMN api.assignment_repository_snapshots.assignment_repository_id IS
    'The provisioned repository this is a snapshot of';
COMMENT ON COLUMN api.assignment_repository_snapshots.effective_closed_at IS
    'The deadline this capture was made for: the student''s grade exception if one applied, else the assignment deadline. Stored rather than re-derived, so a later extension cannot rewrite what this row claims';
COMMENT ON COLUMN api.assignment_repository_snapshots.captured_at IS
    'When the capture was actually observed. Later than the deadline by however long the runner took to get to it; git commit timestamps are user-controlled and cannot narrow that window';
COMMENT ON COLUMN api.assignment_repository_snapshots.commit_sha IS
    'The resolved commit to grade, lowercase hex, SHA-1 or SHA-256. NULL when the capture failed';
COMMENT ON COLUMN api.assignment_repository_snapshots.bundle_uri IS
    'Where the git bundle is stored. A location, not a credential: authorization to fetch it lives in the store, and presigned URLs do not belong here';
COMMENT ON COLUMN api.assignment_repository_snapshots.bundle_sha256 IS
    'SHA-256 of the bundle bytes, so a grader can prove the file they fetched is the file that was captured. NULL when the capture failed';
COMMENT ON COLUMN api.assignment_repository_snapshots.is_verified IS
    'True when the bundle was written, read back, and its digest recomputed to the recorded value. Only verified snapshots are gradeable';
COMMENT ON COLUMN api.assignment_repository_snapshots.error IS
    'Why the capture failed. Required when is_verified is false and forbidden when it is true, so a failure is never an unexplained blank row';
COMMENT ON COLUMN api.assignment_repository_snapshots.superseded_at IS
    'When this stopped being the current snapshot, normally because an extension moved the deadline and a later capture replaced it. NULL means current. Superseded rows are kept: the audit trail is the point';
COMMENT ON COLUMN api.assignment_repository_snapshots.created_at IS
    'When this snapshot record was written';
COMMENT ON COLUMN api.assignment_repository_snapshots.updated_at IS
    'When this snapshot record was last changed';

-- Read-only for students and TAs; the policy above narrows it to their own rows.
GRANT SELECT ON api.assignment_repository_snapshots TO student, ta;

-- The snapshot runner authenticates as faculty and writes here.
GRANT SELECT, INSERT, UPDATE, DELETE ON api.assignment_repository_snapshots TO faculty;

-- ---------------------------------------------------------------------------
-- api.assignment_repository_snapshots_due
-- ---------------------------------------------------------------------------
-- The work queue: which repositories need capturing right now.
--
-- This exists because the effective-deadline expression must live in one place.
-- Extensions move deadlines individually and continuously, so a runner cannot
-- schedule one job at the common deadline -- it has to poll for work that has
-- *become* due, and every client that re-derived "effective deadline" from
-- assignment.closed_at and the exception table would be one more place for the
-- definition to drift out of agreement with the RLS on
-- data.assignment_submission, which is where the definition actually comes from.
--
-- The matching rule is that RLS's, copied deliberately rather than reinvented:
-- an exception applies when it names the same assignment and either its user_id
-- or its team_nickname equals the repository's. NULL is never equal to NULL, so
-- that single predicate gives the individual/team split for free -- an individual
-- repository has a NULL team_nickname and can only match on user, and a team
-- repository has a NULL user_id and can only match on team.
--
-- At most one exception can match: data.assignment_grade_exception's two partial
-- unique indexes make (assignment, user) and (assignment, team) unique, so the
-- LEFT JOIN cannot fan out.
--
-- "Due" is three conditions:
--
--   1. The assignment is not a draft. A draft is not visible to students through
--      api.assignments and is still being written, so its closed_at is not a
--      deadline anyone is working against. The RLS this expression is copied
--      from excludes drafts for the same reason.
--
--   2. The effective deadline has passed.
--
--   3. There is no current, verified snapshot *for that same deadline*.
--
-- The third condition is where a moved deadline is handled, and matching on the
-- deadline rather than merely on the repository is the whole of it. Take a
-- repository snapshotted at its original deadline and then granted an extension:
--
--   * While the new deadline is still in the future, condition 2 fails and the
--     repository is not due. The old snapshot stays current, correctly -- it is
--     the best artifact anyone has until a newer one exists, and a window with no
--     current snapshot at all would be strictly worse.
--
--   * Once the new deadline passes, condition 3 fails to find a snapshot,
--     because the existing one records the *old* effective_closed_at. The
--     repository becomes due again on its own, with no reconciliation step and
--     nothing to remember to re-run. When the new capture lands the runner
--     supersedes the old row, and the partial unique index refuses to let it
--     forget.
--
-- Had this been keyed on the repository alone, an extension granted after a
-- capture would leave the repository permanently not-due, and the student's
-- extension would silently not apply to what was graded -- which is Classroom's
-- bug again, in a new place.
--
-- Failed attempts do not make a repository not-due; that is what makes the
-- runner's retry loop work. failed_attempt_count and last_failed_at are exposed
-- so that "retry forever" can be an operational decision rather than the only
-- available behavior, since a repository that has been deleted on the forge will
-- otherwise fail every few minutes until someone notices.
CREATE OR REPLACE VIEW api.assignment_repository_snapshots_due
WITH (security_barrier = true) AS
    SELECT
        r.id AS assignment_repository_id,
        r.assignment_slug,
        r.is_team,
        r.user_id,
        r.team_nickname,
        r.provider,
        r.provider_repo_id,
        r.provider_full_name,
        a.closed_at AS assignment_closed_at,
        d.effective_closed_at,
        f.failed_attempt_count,
        f.last_failed_at
    FROM data.assignment_repository AS r
    JOIN data.assignment AS a
        ON a.slug = r.assignment_slug
    LEFT JOIN data.assignment_grade_exception AS e
        ON e.assignment_slug = r.assignment_slug
        AND (e.user_id = r.user_id OR e.team_nickname = r.team_nickname)
    -- Naming the expression once, so the three places that need it cannot drift
    -- apart from each other the way copies of it would.
    CROSS JOIN LATERAL (
        SELECT COALESCE(e.closed_at, a.closed_at) AS effective_closed_at
    ) AS d
    CROSS JOIN LATERAL (
        SELECT
            count(*)::int AS failed_attempt_count,
            max(s.captured_at) AS last_failed_at
        FROM data.assignment_repository_snapshot AS s
        WHERE s.assignment_repository_id = r.id
        AND s.effective_closed_at = d.effective_closed_at
        AND NOT s.is_verified
    ) AS f
    WHERE NOT a.is_draft
    AND d.effective_closed_at <= current_timestamp
    AND NOT EXISTS (
        SELECT 1
        FROM data.assignment_repository_snapshot AS s
        WHERE s.assignment_repository_id = r.id
        AND s.effective_closed_at = d.effective_closed_at
        AND s.is_verified
        AND s.superseded_at IS NULL
    );

ALTER VIEW api.assignment_repository_snapshots_due OWNER TO api;

COMMENT ON VIEW api.assignment_repository_snapshots_due IS
    'Repositories whose effective deadline has passed with no current, verified snapshot for that deadline. The snapshot runner''s work queue';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.assignment_repository_id IS
    'The repository to capture, joinable to api.assignment_repositories.id';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.assignment_slug IS
    'The assignment whose deadline has passed';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.is_team IS
    'True when the repository belongs to a team rather than an individual student';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.user_id IS
    'Owning student, set for an individual assignment and NULL otherwise';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.team_nickname IS
    'Owning team, set for a team assignment and NULL otherwise';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider IS
    'Forge hosting the repository, such as github';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider_repo_id IS
    'Forge repository id, which is what the runner should resolve the clone URL from';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.provider_full_name IS
    'Forge repository name such as org/repo. Display only, and expected to go stale';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.assignment_closed_at IS
    'The assignment''s own deadline, before any exception is applied';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.effective_closed_at IS
    'The deadline that governs this repository: the applicable grade exception''s closed_at, else the assignment''s. Record it on the snapshot exactly as it appears here, or the repository will look due forever';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.failed_attempt_count IS
    'How many captures have already failed for this repository at this deadline. Nonzero means retrying, and a large number means something needs a human rather than another attempt';
COMMENT ON COLUMN api.assignment_repository_snapshots_due.last_failed_at IS
    'When the most recent failed capture for this deadline was attempted, or NULL if none has been';

-- Faculty only. This is a work queue for the runner, not something a student has
-- any use for, and it carries other students' effective deadlines -- which the
-- RLS on the underlying tables would filter for a student, but a queue nobody
-- but the runner reads has no reason to be readable at all.
GRANT SELECT ON api.assignment_repository_snapshots_due TO faculty;

-- ---------------------------------------------------------------------------
-- Compatibility version
-- ---------------------------------------------------------------------------
-- schema_compatibility_version reaches 6: the api schema gains two views, which
-- is a change of shape. admin_api_version stays 9, because no RPC was added --
-- the snapshot runner reads a view and writes a view, and PostgREST's ordinary
-- filtering is enough for both.
--
-- Additive, so a client that reads neither view works against 5 and 6 alike and
-- declares {5, 6}; the snapshot runner declares {6} alone. Not `>= 6` -- a floor
-- would sail straight through the next shape that removes something, exactly the
-- way `>= 3` sailed through version 4. See docs/platform-compatibility.md.
CREATE OR REPLACE VIEW api.platform_version AS
    SELECT
        'yelukerest'::text AS platform,
        1::integer AS platform_compatibility_version,
        6::integer AS schema_compatibility_version,
        9::integer AS admin_api_version;

ALTER VIEW api.platform_version OWNER TO api;

COMMENT ON VIEW api.platform_version IS
    'Single-row compatibility metadata for course admin preflight checks';
COMMENT ON COLUMN api.platform_version.platform IS
    'Platform identifier expected by course admin tooling';
COMMENT ON COLUMN api.platform_version.platform_compatibility_version IS
    'Integer compatibility version for Yelukerest platform behavior';
COMMENT ON COLUMN api.platform_version.schema_compatibility_version IS
    'Integer identifying the api schema shape. Check for membership in the set of shapes the client supports, NOT with >=: a shape can lose columns and views, and version 4 did. A client pinned to >= 3 would pass its own preflight against 4 and then fail on its first request.';
COMMENT ON COLUMN api.platform_version.admin_api_version IS
    'Integer compatibility version for generic admin API operations. Only ever grows -- each bump adds an RPC without removing one -- so >= is the correct check.';

-- ---------------------------------------------------------------------------
-- Tell PostgREST the API changed
-- ---------------------------------------------------------------------------
-- PostgREST answers from a schema cache built at startup and does not
-- rediscover new relations on its own. Without this, api.platform_version starts
-- advertising schema shape 6 the instant this commits while
-- GET /rest/assignment_repository_snapshots_due still returns 404 -- the version
-- field would be certifying a shape the API cannot serve.
--
-- NOTIFY is transactional: the payload is delivered at commit and discarded on
-- rollback, so this fires when and only when the migration lands.
NOTIFY pgrst, 'reload schema';
