CREATE TABLE IF NOT EXISTS artifact (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES "user"(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    quiz_id INT REFERENCES quiz(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    slug TEXT NOT NULL
        CHECK (slug ~ '^[a-z0-9][a-z0-9_-]+[a-z0-9]$' AND char_length(slug) < 100),
    title TEXT NOT NULL
        CHECK (char_length(title) < 200),
    description TEXT NOT NULL DEFAULT ''
        CHECK (char_length(description) < 1000),
    url TEXT NOT NULL
        CHECK (text_is_url(url)),
    storage_uri TEXT
        CHECK (storage_uri IS NULL OR char_length(storage_uri) < 1000),
    content_type TEXT
        CHECK (
            content_type IS NULL
            OR content_type ~ '^[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]*/[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]*$'
        ),
    content_length BIGINT
        CHECK (content_length IS NULL OR content_length >= 0),
    checksum_sha256 TEXT
        CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[a-f0-9]{64}$'),
    is_user_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    CONSTRAINT updated_after_created CHECK (updated_at >= created_at),
    CONSTRAINT artifact_user_slug_unique UNIQUE (user_id, slug)
);

DROP INDEX IF EXISTS idx_artifact_user_id_fk;
CREATE INDEX idx_artifact_user_id_fk ON artifact (user_id);

DROP INDEX IF EXISTS idx_artifact_quiz_id_fk;
CREATE INDEX idx_artifact_quiz_id_fk ON artifact (quiz_id);

DROP TRIGGER IF EXISTS tg_artifact_default ON artifact;
CREATE TRIGGER tg_artifact_default
    BEFORE INSERT OR UPDATE
    ON artifact
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
