
CREATE TABLE IF NOT EXISTS assignment_submission (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_slug TEXT NOT NULL CHECK (char_length(assignment_slug) < 100),
    is_team BOOLEAN NOT NULL,
    FOREIGN KEY (assignment_slug, is_team) REFERENCES assignment(slug, is_team)
        ON UPDATE CASCADE,
    user_id INT REFERENCES "user"(id)
        ON UPDATE CASCADE,
    team_nickname TEXT
        CHECK (char_length(team_nickname) < 50)
        REFERENCES team(nickname)
        ON UPDATE CASCADE,
    submitter_user_id INT REFERENCES "user"(id)
        ON UPDATE CASCADE NOT NULL DEFAULT request.user_id(),
    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    updated_at  TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    CONSTRAINT updated_after_created CHECK (updated_at >= created_at),
    CONSTRAINT matches_assignment_is_team CHECK (
        (is_team AND (team_nickname IS NOT NULL) AND (user_id IS NULL))
        OR
        (NOT is_team AND (team_nickname IS NULL) AND (user_id IS NOT NULL))
    ),
    -- If a user creates an individual assignment submission,
    -- the user_id will need to match the sumbmitter_user_id
    CONSTRAINT submitter_matches_user_id CHECK(
        (is_team)
        OR
        (NOT is_team AND (user_id = submitter_user_id))
    ),
    UNIQUE(id, assignment_slug) -- For foreign keys\
);

-- Only one submission per team per assignment
DROP INDEX IF EXISTS assignment_submission_unique_team;
CREATE UNIQUE INDEX assignment_submission_unique_team
    ON assignment_submission (team_nickname, assignment_slug)
    WHERE user_id IS NULL;
-- Only one submission per user per assignment
DROP INDEX IF EXISTS assignment_submission_unique_user;
CREATE UNIQUE INDEX assignment_submission_unique_user
    ON assignment_submission (user_id, assignment_slug)
    WHERE team_nickname IS NULL;

DROP INDEX IF EXISTS idx_assignment_submission_assignment_fk;
CREATE INDEX idx_assignment_submission_assignment_fk
    ON assignment_submission (assignment_slug, is_team);

DROP INDEX IF EXISTS idx_assignment_submission_user_fk;
CREATE INDEX idx_assignment_submission_user_fk
    ON assignment_submission (user_id);

DROP INDEX IF EXISTS idx_assignment_submission_team_fk;
CREATE INDEX idx_assignment_submission_team_fk
    ON assignment_submission (team_nickname);

DROP INDEX IF EXISTS idx_assignment_submission_submitter_fk;
CREATE INDEX idx_assignment_submission_submitter_fk
    ON assignment_submission (submitter_user_id);

CREATE TABLE IF NOT EXISTS assignment_submission_participant (
    assignment_submission_id INT NOT NULL
        REFERENCES assignment_submission(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    user_id INT NOT NULL
        REFERENCES "user"(id)
        ON UPDATE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    PRIMARY KEY (assignment_submission_id, user_id)
);

DROP INDEX IF EXISTS idx_assignment_submission_participant_user_fk;
CREATE INDEX idx_assignment_submission_participant_user_fk
    ON assignment_submission_participant (user_id);

CREATE OR REPLACE FUNCTION fill_assignment_submission_defaults()
RETURNS TRIGGER AS $$
BEGIN
    -- Set default is_team from assignment table
    IF (NEW.is_team IS NULL) THEN
        SELECT is_team INTO NEW.is_team
        FROM data.assignment
        WHERE slug = NEW.assignment_slug;
    END IF;
    -- Set default user_id from request credentials
    IF (NEW.user_id IS NULL AND NOT NEW.is_team ) THEN
        NEW.user_id = request.user_id();
    END IF;
    -- Set default submitter_user_id. This is done in 
    -- the table defaults, but we do it here so that
    -- we can fill in team nickname below.
    IF (NEW.submitter_user_id IS NULL ) THEN
        IF (request.user_id() IS NULL ) THEN
            IF (NEW.user_id IS NOT NULL) THEN
                NEW.submitter_user_id = NEW.user_id;
            END IF;
        ELSE
            NEW.submitter_user_id = request.user_id();
        END IF;
    END IF;
    -- Set default team_nickname from user table
    IF (NEW.is_team AND NEW.team_nickname IS NULL) THEN
        SELECT u.team_nickname INTO NEW.team_nickname
        FROM data."user" AS u
        WHERE u.id = NEW.submitter_user_id;
    END IF;
    NEW.updated_at = current_timestamp;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;


DROP TRIGGER IF EXISTS tg_assignment_submission_default ON assignment_submission;
CREATE TRIGGER tg_assignment_submission_default
    BEFORE INSERT OR UPDATE
    ON assignment_submission
    FOR EACH ROW
EXECUTE FUNCTION fill_assignment_submission_defaults();

CREATE OR REPLACE FUNCTION refresh_assignment_submission_participants()
RETURNS TRIGGER AS $$
BEGIN
    -- Submission participants are an insert-time snapshot. Later team roster
    -- changes must not rewrite historical submitted work.
    DELETE FROM data.assignment_submission_participant
    WHERE assignment_submission_id = NEW.id;

    IF (NEW.is_team) THEN
        INSERT INTO data.assignment_submission_participant (assignment_submission_id, user_id)
        SELECT NEW.id, u.id
        FROM data."user" AS u
        WHERE u.team_nickname = NEW.team_nickname;
    ELSE
        INSERT INTO data.assignment_submission_participant (assignment_submission_id, user_id)
        SELECT NEW.id, NEW.user_id
        WHERE NEW.user_id IS NOT NULL;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;

DROP TRIGGER IF EXISTS tg_assignment_submission_participants ON assignment_submission;
CREATE TRIGGER tg_assignment_submission_participants
    AFTER INSERT
    ON assignment_submission
    FOR EACH ROW
EXECUTE FUNCTION refresh_assignment_submission_participants();

INSERT INTO assignment_submission_participant (assignment_submission_id, user_id)
SELECT ass_sub.id, ass_sub.user_id
FROM assignment_submission AS ass_sub
WHERE NOT ass_sub.is_team
AND ass_sub.user_id IS NOT NULL
UNION
SELECT ass_sub.id, u.id
FROM assignment_submission AS ass_sub
JOIN "user" AS u
ON u.team_nickname = ass_sub.team_nickname
WHERE ass_sub.is_team
ON CONFLICT DO NOTHING;
