-- Append-only audit history for assignment field submission writes.
-- Follows the grade_event pattern: an AFTER trigger on the source
-- table appends one event row per mutation, and the history table
-- itself rejects UPDATE and DELETE. We record a hash and length of
-- the body (not the body itself) so history stays small while still
-- letting us detect lost or overwritten work.
CREATE TABLE IF NOT EXISTS assignment_field_submission_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL
        CHECK (event_type = ANY (ARRAY['submitted', 'revised', 'deleted'])),
    operation TEXT NOT NULL
        CHECK (operation = ANY (ARRAY['insert', 'update', 'delete'])),
    assignment_submission_id INT NOT NULL,
    assignment_field_slug TEXT NOT NULL
        CHECK (char_length(assignment_field_slug) < 100),
    assignment_slug TEXT NOT NULL
        CHECK (char_length(assignment_slug) < 100),
    body_sha256 TEXT NOT NULL
        CHECK (body_sha256 ~ '^[a-f0-9]{64}$'),
    body_length INT NOT NULL
        CHECK (body_length >= 0),
    submitter_user_id INT,
    submission_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submission_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    created_by_user_id INT
);

DROP INDEX IF EXISTS idx_assignment_field_submission_event_natural_key;
CREATE INDEX idx_assignment_field_submission_event_natural_key
    ON assignment_field_submission_event (assignment_submission_id, assignment_field_slug, created_at, id);

DROP INDEX IF EXISTS idx_assignment_field_submission_event_actor_fk;
CREATE INDEX idx_assignment_field_submission_event_actor_fk
    ON assignment_field_submission_event (created_by_user_id);

CREATE OR REPLACE FUNCTION prevent_assignment_field_submission_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'assignment field submission event history is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tg_assignment_field_submission_event_append_only ON assignment_field_submission_event;
CREATE TRIGGER tg_assignment_field_submission_event_append_only
    BEFORE UPDATE OR DELETE
    ON assignment_field_submission_event
    FOR EACH ROW
EXECUTE FUNCTION prevent_assignment_field_submission_event_mutation();

CREATE OR REPLACE FUNCTION record_assignment_field_submission_event()
RETURNS TRIGGER AS $$
DECLARE
    submission_row data.assignment_field_submission%ROWTYPE;
    event_kind TEXT;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        submission_row := OLD;
        event_kind := 'deleted';
    ELSE
        submission_row := NEW;
        IF (TG_OP = 'INSERT') THEN
            event_kind := 'submitted';
        ELSE
            event_kind := 'revised';
        END IF;
    END IF;

    INSERT INTO data.assignment_field_submission_event (
        event_type,
        operation,
        assignment_submission_id,
        assignment_field_slug,
        assignment_slug,
        body_sha256,
        body_length,
        submitter_user_id,
        submission_created_at,
        submission_updated_at,
        created_by_user_id
    )
    VALUES (
        event_kind,
        lower(TG_OP),
        submission_row.assignment_submission_id,
        submission_row.assignment_field_slug,
        submission_row.assignment_slug,
        encode(public.digest(submission_row.body, 'sha256'), 'hex'),
        octet_length(submission_row.body),
        submission_row.submitter_user_id,
        submission_row.created_at,
        submission_row.updated_at,
        request.user_id()
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;

DROP TRIGGER IF EXISTS tg_assignment_field_submission_event_history ON assignment_field_submission;
CREATE TRIGGER tg_assignment_field_submission_event_history
    AFTER INSERT OR UPDATE OR DELETE
    ON assignment_field_submission
    FOR EACH ROW
EXECUTE FUNCTION record_assignment_field_submission_event();
