CREATE TABLE IF NOT EXISTS assignment_grade_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL
        CHECK (event_type = ANY (ARRAY['recorded', 'corrected', 'voided'])),
    operation TEXT NOT NULL
        CHECK (operation = ANY (ARRAY['insert', 'update', 'delete'])),
    assignment_submission_id INT NOT NULL,
    assignment_slug TEXT NOT NULL
        CHECK (char_length(assignment_slug) < 100),
    points_possible SMALLINT NOT NULL
        CHECK (points_possible >= 0),
    points REAL NOT NULL,
    description TEXT,
    grade_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    grade_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    created_by_user_id INT,
    source TEXT NOT NULL DEFAULT 'data.assignment_grade',
    reason TEXT,
    import_id TEXT,
    CONSTRAINT assignment_grade_event_points_in_range
        CHECK (points >= 0 AND points <= points_possible)
);

DROP INDEX IF EXISTS idx_assignment_grade_event_natural_key;
CREATE INDEX idx_assignment_grade_event_natural_key
    ON assignment_grade_event (assignment_submission_id, created_at, id);

DROP INDEX IF EXISTS idx_assignment_grade_event_actor_fk;
CREATE INDEX idx_assignment_grade_event_actor_fk
    ON assignment_grade_event (created_by_user_id);

CREATE TABLE IF NOT EXISTS quiz_grade_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL
        CHECK (event_type = ANY (ARRAY['recorded', 'corrected', 'voided'])),
    operation TEXT NOT NULL
        CHECK (operation = ANY (ARRAY['insert', 'update', 'delete'])),
    quiz_id INT NOT NULL,
    user_id INT NOT NULL,
    points REAL NOT NULL,
    points_possible SMALLINT NOT NULL
        CHECK (points_possible >= 0),
    description TEXT,
    grade_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    grade_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    created_by_user_id INT,
    source TEXT NOT NULL DEFAULT 'data.quiz_grade',
    reason TEXT,
    import_id TEXT,
    CONSTRAINT quiz_grade_event_points_in_range
        CHECK (points >= 0 AND points <= points_possible)
);

DROP INDEX IF EXISTS idx_quiz_grade_event_natural_key;
CREATE INDEX idx_quiz_grade_event_natural_key
    ON quiz_grade_event (quiz_id, user_id, created_at, id);

DROP INDEX IF EXISTS idx_quiz_grade_event_actor_fk;
CREATE INDEX idx_quiz_grade_event_actor_fk
    ON quiz_grade_event (created_by_user_id);

CREATE TABLE IF NOT EXISTS grade_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL
        CHECK (event_type = ANY (ARRAY['recorded', 'corrected', 'voided'])),
    operation TEXT NOT NULL
        CHECK (operation = ANY (ARRAY['insert', 'update', 'delete'])),
    snapshot_slug TEXT NOT NULL,
    user_id INT NOT NULL,
    points REAL NOT NULL,
    description TEXT,
    grade_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    grade_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    created_by_user_id INT,
    source TEXT NOT NULL DEFAULT 'data.grade',
    reason TEXT,
    import_id TEXT,
    CONSTRAINT grade_event_points_finite_nonnegative
        CHECK (points >= 0 AND points < 'Infinity'::real)
);

DROP INDEX IF EXISTS idx_grade_event_natural_key;
CREATE INDEX idx_grade_event_natural_key
    ON grade_event (snapshot_slug, user_id, created_at, id);

DROP INDEX IF EXISTS idx_grade_event_actor_fk;
CREATE INDEX idx_grade_event_actor_fk
    ON grade_event (created_by_user_id);

CREATE OR REPLACE FUNCTION prevent_grade_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'grade event history is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tg_assignment_grade_event_append_only ON assignment_grade_event;
CREATE TRIGGER tg_assignment_grade_event_append_only
    BEFORE UPDATE OR DELETE
    ON assignment_grade_event
    FOR EACH ROW
EXECUTE FUNCTION prevent_grade_event_mutation();

DROP TRIGGER IF EXISTS tg_quiz_grade_event_append_only ON quiz_grade_event;
CREATE TRIGGER tg_quiz_grade_event_append_only
    BEFORE UPDATE OR DELETE
    ON quiz_grade_event
    FOR EACH ROW
EXECUTE FUNCTION prevent_grade_event_mutation();

DROP TRIGGER IF EXISTS tg_grade_event_append_only ON grade_event;
CREATE TRIGGER tg_grade_event_append_only
    BEFORE UPDATE OR DELETE
    ON grade_event
    FOR EACH ROW
EXECUTE FUNCTION prevent_grade_event_mutation();

CREATE OR REPLACE FUNCTION record_assignment_grade_event()
RETURNS TRIGGER AS $$
DECLARE
    grade_row data.assignment_grade%ROWTYPE;
    event_kind TEXT;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        grade_row := OLD;
        event_kind := 'voided';
    ELSE
        grade_row := NEW;
        IF (TG_OP = 'INSERT') THEN
            event_kind := 'recorded';
        ELSE
            event_kind := 'corrected';
        END IF;
    END IF;

    INSERT INTO data.assignment_grade_event (
        event_type,
        operation,
        assignment_submission_id,
        assignment_slug,
        points_possible,
        points,
        description,
        grade_created_at,
        grade_updated_at,
        created_by_user_id
    )
    VALUES (
        event_kind,
        lower(TG_OP),
        grade_row.assignment_submission_id,
        grade_row.assignment_slug,
        grade_row.points_possible,
        grade_row.points,
        grade_row.description,
        grade_row.created_at,
        grade_row.updated_at,
        request.user_id()
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;

DROP TRIGGER IF EXISTS tg_assignment_grade_event_history ON assignment_grade;
CREATE TRIGGER tg_assignment_grade_event_history
    AFTER INSERT OR UPDATE OR DELETE
    ON assignment_grade
    FOR EACH ROW
EXECUTE FUNCTION record_assignment_grade_event();

CREATE OR REPLACE FUNCTION record_quiz_grade_event()
RETURNS TRIGGER AS $$
DECLARE
    grade_row data.quiz_grade%ROWTYPE;
    event_kind TEXT;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        grade_row := OLD;
        event_kind := 'voided';
    ELSE
        grade_row := NEW;
        IF (TG_OP = 'INSERT') THEN
            event_kind := 'recorded';
        ELSE
            event_kind := 'corrected';
        END IF;
    END IF;

    INSERT INTO data.quiz_grade_event (
        event_type,
        operation,
        quiz_id,
        user_id,
        points,
        points_possible,
        description,
        grade_created_at,
        grade_updated_at,
        created_by_user_id
    )
    VALUES (
        event_kind,
        lower(TG_OP),
        grade_row.quiz_id,
        grade_row.user_id,
        grade_row.points,
        grade_row.points_possible,
        grade_row.description,
        grade_row.created_at,
        grade_row.updated_at,
        request.user_id()
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;

DROP TRIGGER IF EXISTS tg_quiz_grade_event_history ON quiz_grade;
CREATE TRIGGER tg_quiz_grade_event_history
    AFTER INSERT OR UPDATE OR DELETE
    ON quiz_grade
    FOR EACH ROW
EXECUTE FUNCTION record_quiz_grade_event();

CREATE OR REPLACE FUNCTION record_grade_event()
RETURNS TRIGGER AS $$
DECLARE
    grade_row data.grade%ROWTYPE;
    event_kind TEXT;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        grade_row := OLD;
        event_kind := 'voided';
    ELSE
        grade_row := NEW;
        IF (TG_OP = 'INSERT') THEN
            event_kind := 'recorded';
        ELSE
            event_kind := 'corrected';
        END IF;
    END IF;

    INSERT INTO data.grade_event (
        event_type,
        operation,
        snapshot_slug,
        user_id,
        points,
        description,
        grade_created_at,
        grade_updated_at,
        created_by_user_id
    )
    VALUES (
        event_kind,
        lower(TG_OP),
        grade_row.snapshot_slug,
        grade_row.user_id,
        grade_row.points,
        grade_row.description,
        grade_row.created_at,
        grade_row.updated_at,
        request.user_id()
    );

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = data, pg_temp;

DROP TRIGGER IF EXISTS tg_grade_event_history ON grade;
CREATE TRIGGER tg_grade_event_history
    AFTER INSERT OR UPDATE OR DELETE
    ON grade
    FOR EACH ROW
EXECUTE FUNCTION record_grade_event();
