-- Append-only record of MCP grants a user has disconnected (issue #277).
--
-- Revoking consent at Hydra kills the refresh token immediately, but an
-- access token already in an agent's hands keeps working: mcpapp verifies it
-- offline against the JWKS, so there is nothing to consult that would say
-- "this grant is gone". That is the hole this table closes. Every ~10 minutes
-- mcpapp must exchange the OAuth token for a fresh internal credential, and
-- api.issue_user_jwt_for_mcp refuses to mint when a row here covers the
-- (user, client) pair. So "disconnect" means: refresh dies now, and the last
-- internal credential expires within its own short lifetime.
--
-- Rows are keyed by client_id rather than by token, because the user's
-- intent is about an application ("disconnect Claude"), not about whichever
-- token that application happens to hold.
CREATE TABLE IF NOT EXISTS mcp_grant_revocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Who disconnected the app. No foreign key, so the audit trail survives
    -- user deletion, matching mcp_jwt_mint_event.
    user_id INT NOT NULL,
    netid TEXT NOT NULL
        CHECK (char_length(netid) < 100),
    -- The OAuth client that was disconnected.
    client_id TEXT NOT NULL
        CHECK (char_length(client_id) > 0 AND char_length(client_id) <= 500),
    -- Kept for the audit trail: client_id is a UUID to a human.
    client_name TEXT
        CHECK (char_length(client_name) <= 500),
    -- Everything the grant could reach at the moment it was cut off.
    scopes TEXT
        CHECK (char_length(scopes) <= 1024),
    revoked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp
);

-- The mint path checks this on every exchange, so the lookup has to be cheap.
DROP INDEX IF EXISTS idx_mcp_grant_revocation_lookup;
CREATE INDEX idx_mcp_grant_revocation_lookup
    ON mcp_grant_revocation (user_id, client_id, revoked_at DESC);

-- History, not state: a revocation that could be edited or deleted would be
-- worthless as an audit trail, and the mint check reads it as fact.
CREATE OR REPLACE FUNCTION mcp_grant_revocation_is_append_only()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'mcp_grant_revocation is append-only'
        USING ERRCODE = '42501';
END;
$$;

DROP TRIGGER IF EXISTS mcp_grant_revocation_no_update ON mcp_grant_revocation;
CREATE TRIGGER mcp_grant_revocation_no_update
    BEFORE UPDATE OR DELETE ON mcp_grant_revocation
    FOR EACH ROW EXECUTE FUNCTION mcp_grant_revocation_is_append_only();
