-- Append-only audit history of internal user JWTs minted for the MCP
-- service (issue #263, ADR 0001). Every call to
-- api.issue_user_jwt_for_mcp that produces a token appends exactly one
-- row here in the same transaction, so a compromise of the mcpapp
-- minting credential is always visible in this history. Follows the
-- assignment_field_submission_event pattern: the history table itself
-- rejects UPDATE and DELETE. There is deliberately no foreign key on
-- user_id so audit rows survive user deletion.
CREATE TABLE IF NOT EXISTS mcp_jwt_mint_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Who the token was minted for.
    user_id INT NOT NULL,
    netid TEXT NOT NULL
        CHECK (char_length(netid) < 100),
    user_role TEXT NOT NULL
        CHECK (char_length(user_role) < 100),
    -- Space-separated scopes granted in the minted token.
    scopes TEXT NOT NULL
        CHECK (char_length(scopes) <= 1024),
    -- The jti claim of the minted internal JWT.
    jti TEXT NOT NULL
        CHECK (jti ~ '^[0-9a-f-]{36}$'),
    -- The app_name claim of the calling service credential.
    caller_app_name TEXT NOT NULL
        CHECK (char_length(caller_app_name) < 100),
    -- External (OAuth/bearer) token identity that was exchanged for this
    -- internal JWT, when provided by the caller. Nullable in phase 0.
    external_issuer TEXT
        CHECK (char_length(external_issuer) <= 500),
    external_sub TEXT
        CHECK (char_length(external_sub) <= 500),
    external_jti TEXT
        CHECK (char_length(external_jti) <= 500),
    external_client_id TEXT
        CHECK (char_length(external_client_id) <= 500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp
);

-- Supports the mint-rate anomaly report (per-caller time windows).
DROP INDEX IF EXISTS idx_mcp_jwt_mint_event_caller_window;
CREATE INDEX idx_mcp_jwt_mint_event_caller_window
    ON mcp_jwt_mint_event (caller_app_name, created_at, user_id);

DROP INDEX IF EXISTS idx_mcp_jwt_mint_event_user_fk;
CREATE INDEX idx_mcp_jwt_mint_event_user_fk
    ON mcp_jwt_mint_event (user_id);

CREATE OR REPLACE FUNCTION prevent_mcp_jwt_mint_event_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'mcp jwt mint event history is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tg_mcp_jwt_mint_event_append_only ON mcp_jwt_mint_event;
CREATE TRIGGER tg_mcp_jwt_mint_event_append_only
    BEFORE UPDATE OR DELETE
    ON mcp_jwt_mint_event
    FOR EACH ROW
EXECUTE FUNCTION prevent_mcp_jwt_mint_event_mutation();
