-- Which repository belongs to which student for which assignment (#312).
--
-- GitHub Classroom shuts down 2026-08-28, so a course repo has to provision
-- student repositories itself. That needs an authoritative record of the
-- mapping, and it belongs here: the effective deadline that governs a
-- repository is `assignment_grade_exception.closed_at` else
-- `assignment.closed_at`, and submissions, grades, extensions, users and teams
-- are all already in this database. A JSON file in a course repo diverges from
-- them the first time enrollment changes, a handle is renamed, an extension is
-- granted, or a repo is recreated.
--
-- Consumer: yale-mgt-656-fall-2026/admin#21.
--
-- Deployed inside a transaction Zapadka opens and commits.
-- Do not write BEGIN, COMMIT, ROLLBACK, or SAVEPOINT here.

-- ---------------------------------------------------------------------------
-- data.assignment_repository
-- ---------------------------------------------------------------------------
-- Course scope is the database. This platform serves MGT 656 and MGT 858, but
-- as separate deployments -- there is no `course` table and never has been --
-- so the issue's "(course, assignment, student)" uniqueness is exactly
-- (assignment, student) here. Nothing about the shape is 656-specific.
--
-- Nothing about the shape is GitHub-specific either. `provider` is a column, so
-- a second forge is a new value rather than a new table.
CREATE TABLE data.assignment_repository (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    assignment_slug TEXT NOT NULL CHECK (char_length(assignment_slug) < 100),

    -- Carried and foreign-keyed to (assignment.slug, assignment.is_team) for
    -- the same reason data.assignment_submission carries it: it makes a team
    -- repository on an individual assignment unrepresentable rather than merely
    -- discouraged. Unlike assignment_submission there is no trigger filling it
    -- in from the assignment, because the writer here is faculty provisioning
    -- tooling that already knows which kind of assignment it is provisioning,
    -- and a wrong answer should be refused rather than silently corrected.
    is_team BOOLEAN NOT NULL,
    FOREIGN KEY (assignment_slug, is_team) REFERENCES data.assignment(slug, is_team)
        ON UPDATE CASCADE,

    -- Exactly one of these, the split copied from data.assignment_submission.
    user_id INT REFERENCES data."user"(id)
        ON UPDATE CASCADE,
    team_nickname TEXT
        CHECK (char_length(team_nickname) < 50)
        REFERENCES data.team(nickname)
        ON UPDATE CASCADE,

    -- The forge. Constrained to a slug-shaped token so it stays a stable key a
    -- client can branch on, rather than free text that arrives as 'GitHub' on
    -- one run and 'github.com' on the next.
    provider TEXT NOT NULL DEFAULT 'github'
        CHECK (provider ~ '^[a-z][a-z0-9_-]{0,31}$'),

    -- Identity. GitHub's repository id is a positive int64 and survives every
    -- rename, transfer, and visibility change a repository can undergo; a
    -- name-based key silently reattaches to whatever holds the name next.
    -- GitLab, Gitea and Forgejo are also int64, so BIGINT covers the forges
    -- `provider` is likely to name. A forge with string ids (Bitbucket uses
    -- UUIDs) would need a migration -- accepted deliberately, because TEXT here
    -- would let '123', '0123' and ' 123 ' be three identities for one
    -- repository and the unique index below would not catch it.
    provider_repo_id BIGINT NOT NULL CHECK (provider_repo_id > 0),

    -- Display, and mutable on purpose: 'org/repo' today, something else after
    -- the next rename. Nothing keys on it. The browser URL is derivable
    -- (https://github.com/<full_name>) and is deliberately not stored, so there
    -- is one fewer copy to go stale.
    provider_full_name TEXT NOT NULL
        CHECK (char_length(provider_full_name) BETWEEN 1 AND 255),

    -- The forge account the repository was provisioned for, also identity
    -- rather than a handle. Nullable, and legitimately so: a repository is
    -- created before its student accepts the invitation, so the numeric account
    -- id is not known at provisioning time. A team row generally has no single
    -- account and leaves it NULL.
    provider_user_id BIGINT CHECK (provider_user_id > 0),

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT current_timestamp,
    CONSTRAINT updated_after_created CHECK (updated_at >= created_at),

    CONSTRAINT matches_assignment_is_team CHECK (
        (is_team AND (team_nickname IS NOT NULL) AND (user_id IS NULL))
        OR
        (NOT is_team AND (team_nickname IS NULL) AND (user_id IS NOT NULL))
    ),

    -- One row per repository, per forge. This is what makes reconciliation able
    -- to ask "what did we provision" and get an answer, rather than deriving
    -- identity by sed-ing a repository name.
    CONSTRAINT assignment_repository_unique_provider_repo
        UNIQUE (provider, provider_repo_id)
);

-- One repository per student per assignment, and per team per assignment. The
-- partial predicates are the shape data.assignment_submission uses, and they
-- are needed for the same reason: NULLs are distinct in a unique index, so a
-- plain UNIQUE(user_id, assignment_slug) would admit every team row.
--
-- `provider` is deliberately absent from both keys. A student has one
-- repository for an assignment, full stop; moving a course to another forge is
-- an update of these rows, not a second row per student.
CREATE UNIQUE INDEX assignment_repository_unique_user
    ON data.assignment_repository (user_id, assignment_slug)
    WHERE team_nickname IS NULL;

CREATE UNIQUE INDEX assignment_repository_unique_team
    ON data.assignment_repository (team_nickname, assignment_slug)
    WHERE user_id IS NULL;

-- Plain btree indexes covering each foreign key's referencing columns, in the
-- constraint's own column order. tests/db/foreign-key-indexes.sql requires
-- this of every foreign key in the `data` schema, and the partial unique
-- indexes above do not satisfy it -- that test ignores indexes with a
-- predicate, correctly, since a partial index cannot serve the referential
-- integrity check.
CREATE INDEX idx_assignment_repository_assignment_fk
    ON data.assignment_repository (assignment_slug, is_team);

CREATE INDEX idx_assignment_repository_user_fk
    ON data.assignment_repository (user_id);

CREATE INDEX idx_assignment_repository_team_fk
    ON data.assignment_repository (team_nickname);

-- The generic updated_at trigger, already deployed and already routed through
-- data.touched_at, so this table inherits the #308 fix rather than restating
-- it. No new function: an `updated_at` that never moves is worse than none, and
-- this is the whole of what this table needs.
CREATE TRIGGER tg_assignment_repository_update_timestamps
    BEFORE INSERT OR UPDATE
    ON data.assignment_repository
    FOR EACH ROW
EXECUTE FUNCTION data.update_updated_at_column();

COMMENT ON TABLE data.assignment_repository IS
    'Which forge repository belongs to which student or team for which assignment';

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON data.assignment_repository TO api;

ALTER TABLE data.assignment_repository ENABLE ROW LEVEL SECURITY;

-- Faculty read and write. A student reads their own row and nothing else.
--
-- Students can see it rather than being locked out entirely, because the row is
-- a fact about the student's own work that they can already see on the forge,
-- and because the support path this table exists to serve runs in both
-- directions: reconciliation has to be able to answer "is this the repository
-- you provisioned for me" without a faculty member in the loop. Read-only is
-- the whole of it -- a student who could write here could hand in another
-- repository after the deadline, which is exactly the property that made
-- name-derived identity unsafe.
--
-- Team membership is evaluated live, against data."user".team_nickname, and not
-- snapshotted the way data.assignment_submission_participant snapshots a
-- submission. The two are different questions. A submission is historical work
-- whose authorship must not be rewritten by a later roster change; a repository
-- is a live grant, and a student moved off a team loses access to the team's
-- repository on the forge at the same moment. Live membership is the answer
-- that stays true here.
CREATE POLICY assignment_repository_access_policy ON data.assignment_repository TO api
USING (
    (request.user_role() = 'faculty')
    OR
    (
        request.user_role() = ANY('{student,ta}'::text[])
        AND (
            (NOT is_team AND request.user_id() = user_id)
            OR
            (is_team AND EXISTS (
                SELECT 1
                FROM data."user" AS u
                WHERE u.id = request.user_id()
                AND u.team_nickname = assignment_repository.team_nickname
            ))
        )
    )
) WITH CHECK (
    request.user_role() = 'faculty'
);

-- ---------------------------------------------------------------------------
-- api.assignment_repositories
-- ---------------------------------------------------------------------------
-- Owned by `api` so the policy above is what governs reads through PostgREST.
CREATE OR REPLACE VIEW api.assignment_repositories AS
    SELECT * FROM data.assignment_repository;

ALTER VIEW api.assignment_repositories OWNER TO api;

-- tests/db/structure.sql requires a comment on every api view and every one of
-- its columns.
COMMENT ON VIEW api.assignment_repositories IS
    'Forge repositories provisioned for a student or team for an assignment';
COMMENT ON COLUMN api.assignment_repositories.id IS
    'Surrogate key for this repository record';
COMMENT ON COLUMN api.assignment_repositories.assignment_slug IS
    'The assignment this repository was provisioned for';
COMMENT ON COLUMN api.assignment_repositories.is_team IS
    'True when the repository belongs to a team, matching the assignment kind';
COMMENT ON COLUMN api.assignment_repositories.user_id IS
    'Owning student, set when the assignment is individual and NULL otherwise';
COMMENT ON COLUMN api.assignment_repositories.team_nickname IS
    'Owning team, set when the assignment is a team assignment and NULL otherwise';
COMMENT ON COLUMN api.assignment_repositories.provider IS
    'Forge hosting the repository, such as github';
COMMENT ON COLUMN api.assignment_repositories.provider_repo_id IS
    'Forge repository id. Identity: it survives renames and transfers, and everything keys on it rather than on the name';
COMMENT ON COLUMN api.assignment_repositories.provider_full_name IS
    'Forge repository name such as org/repo. Display only, and mutable: students rename accounts and repositories get renamed';
COMMENT ON COLUMN api.assignment_repositories.provider_user_id IS
    'Forge account id the repository was provisioned for. Identity rather than a handle, and NULL until the account is known';
COMMENT ON COLUMN api.assignment_repositories.created_at IS
    'When this repository record was created';
COMMENT ON COLUMN api.assignment_repositories.updated_at IS
    'When this repository record was last changed';

-- Read-only for students and TAs; the policy above narrows it to their own row.
GRANT SELECT ON api.assignment_repositories TO student, ta;

-- Faculty provisioning tooling writes here.
GRANT SELECT, INSERT, UPDATE, DELETE ON api.assignment_repositories TO faculty;

-- ---------------------------------------------------------------------------
-- Compatibility version
-- ---------------------------------------------------------------------------
-- schema_compatibility_version reaches 5: the api schema gains a view, which is
-- a change of shape. admin_api_version stays 9, because no RPC was added.
--
-- The two are read with different operators, and this bump is why the schema
-- one cannot be a floor. A course client that needs api.assignment_repositories
-- declares {5}; one that does not care declares {4, 5}. A client declaring
-- `>= 4` would pass its own preflight against a deployment that predates this
-- migration -- version 4 has no such view -- and then take a PostgREST 404 on
-- its first request, which is the exact failure the preflight exists to catch.
-- See docs/platform-compatibility.md.
CREATE OR REPLACE VIEW api.platform_version AS
    SELECT
        'yelukerest'::text AS platform,
        1::integer AS platform_compatibility_version,
        5::integer AS schema_compatibility_version,
        9::integer AS admin_api_version;

ALTER VIEW api.platform_version OWNER TO api;

COMMENT ON VIEW api.platform_version IS
    'Single-row compatibility metadata for course admin preflight checks';
COMMENT ON COLUMN api.platform_version.platform IS
    'Platform identifier expected by course admin tooling';
COMMENT ON COLUMN api.platform_version.platform_compatibility_version IS
    'Integer compatibility version for Yelukerest platform behavior';
COMMENT ON COLUMN api.platform_version.schema_compatibility_version IS
    'Integer identifying the api schema shape. Check for membership in the set of shapes the client supports, NOT with >=: a shape can lose columns and views, and version 4 did. A client pinned to >= 3 would pass its own preflight against 4 and then fail on its first request.';
COMMENT ON COLUMN api.platform_version.admin_api_version IS
    'Integer compatibility version for generic admin API operations. Only ever grows -- each bump adds an RPC without removing one -- so >= is the correct check.';

-- ---------------------------------------------------------------------------
-- Tell PostgREST the API changed
-- ---------------------------------------------------------------------------
-- PostgREST answers from a schema cache built at startup and does not
-- rediscover a new table on its own. Without this, api.platform_version starts
-- advertising schema shape 5 the instant this commits while
-- GET /rest/assignment_repositories still returns 404 -- the version field
-- would be certifying a shape the API cannot serve.
--
-- NOTIFY is transactional: the payload is delivered at commit and discarded on
-- rollback, so this fires when and only when the migration lands. The channel
-- is `pgrst` because db-channel-enabled defaults to true there and this
-- deployment does not override it; an unheard NOTIFY costs nothing.
NOTIFY pgrst, 'reload schema';
