-- Personal access tokens for direct API access (issues #314-#317).
--
-- Why this exists: a student writing a script -- or, increasingly, the AI
-- assistant writing it with them -- had no usable credential. The documented
-- path was "copy a 60-minute token out of /auth/jwt and repeat every hour",
-- with no refresh and no revocation, so an assistant that hit a 401 mid-task
-- could not recover without a human returning to a browser.
--
-- A personal access token is a new CREDENTIAL, not a new authorization model.
-- Nothing here decides what a caller may do: that stays with the `scopes`
-- claim, api.check_request_jwt, and row-level security, exactly as for MCP.
--
-- The long-lived token never reaches PostgREST. It is exchanged for the same
-- one-hour JWT the browser already uses, which is what caps exposure after a
-- revocation at one hour rather than the life of the token.

-- ---------------------------------------------------------------------------
-- Storage
-- ---------------------------------------------------------------------------
CREATE TABLE data.user_api_token (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL
        REFERENCES data."user"(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    -- Shown in the UI so a person can tell two tokens apart, and the lookup
    -- key at exchange time. Not a secret.
    token_prefix TEXT NOT NULL UNIQUE
        CHECK (token_prefix ~ '^yk_[0-9a-f]{8}$'),
    -- SHA-256 of the secret half. The secret itself is returned exactly once,
    -- at creation, and never stored.
    token_hash BYTEA NOT NULL,
    name TEXT NOT NULL
        CHECK (char_length(name) BETWEEN 1 AND 100),
    -- Same vocabulary as MCP (docs/mcp-writes.md). Deliberately not a new set:
    -- one scope language across both credential paths is worth more than
    -- finer granularity here.
    scopes TEXT[] NOT NULL
        CHECK (
            cardinality(scopes) BETWEEN 1 AND 8
            AND scopes <@ ARRAY[
                'course:read', 'grades:read', 'submissions:read', 'submissions:write'
            ]::TEXT[]
        ),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- The only signal that a token someone forgot about is still in use, which
    -- is the main practical defence for a credential that lives for months.
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT user_api_token_expires_after_creation
        CHECK (expires_at > created_at)
);

-- tests/db/foreign-key-indexes.sql requires an index led by the referencing
-- column, and ignores partial ones.
CREATE INDEX user_api_token_user_id_idx ON data.user_api_token (user_id);

COMMENT ON TABLE data.user_api_token IS
    'Long-lived revocable credentials for direct API access. Exchanged for a short-lived JWT; never presented to PostgREST directly.';
COMMENT ON COLUMN data.user_api_token.token_hash IS
    'SHA-256 of the secret half. Never exposed through the api schema.';
COMMENT ON COLUMN data.user_api_token.last_used_at IS
    'Updated on every successful exchange. The only evidence a forgotten token is still live.';

ALTER TABLE data.user_api_token OWNER TO yelukerest_migrator;
GRANT SELECT, INSERT, UPDATE, DELETE ON data.user_api_token TO api;

ALTER TABLE data.user_api_token ENABLE ROW LEVEL SECURITY;

-- A person manages their own tokens. Faculty see everyone's, because a leaked
-- credential is a course-wide problem and revoking it must not require the
-- student to be reachable. Nobody reads another person's token_hash, which the
-- api view withholds from everyone regardless.
CREATE POLICY user_api_token_access_policy
    ON data.user_api_token TO api
USING (
    request.user_role() = 'faculty'
    OR user_id = request.user_id()
)
WITH CHECK (
    request.user_role() = 'faculty'
    OR user_id = request.user_id()
);

-- ---------------------------------------------------------------------------
-- API view -- deliberately without token_hash
-- ---------------------------------------------------------------------------
CREATE VIEW api.user_api_tokens AS
    SELECT
        t.id,
        t.user_id,
        t.token_prefix,
        t.name,
        t.scopes,
        t.created_at,
        t.expires_at,
        t.last_used_at,
        t.revoked_at,
        (t.revoked_at IS NULL AND t.expires_at > current_timestamp) AS is_active
    FROM data.user_api_token t;

ALTER VIEW api.user_api_tokens OWNER TO api;

COMMENT ON VIEW api.user_api_tokens IS
    'Personal access tokens visible to their owner (faculty see all). Never exposes the secret or its hash.';

COMMENT ON COLUMN api.user_api_tokens.token_prefix IS
    'Public identifier of the token, shown so a person can tell two tokens apart';
COMMENT ON COLUMN api.user_api_tokens.name IS
    'Human-supplied label for the token';
COMMENT ON COLUMN api.user_api_tokens.scopes IS
    'Scopes this token may mint into a JWT. Fixed at creation and never editable.';
COMMENT ON COLUMN api.user_api_tokens.id IS 'Token identifier';
COMMENT ON COLUMN api.user_api_tokens.user_id IS 'Owner of the token';
COMMENT ON COLUMN api.user_api_tokens.created_at IS 'When the token was created';
COMMENT ON COLUMN api.user_api_tokens.expires_at IS 'When the token stops being exchangeable';
COMMENT ON COLUMN api.user_api_tokens.last_used_at IS
    'Last successful exchange. The only evidence a forgotten token is still live.';
COMMENT ON COLUMN api.user_api_tokens.revoked_at IS 'When the token was revoked, if it was';
COMMENT ON COLUMN api.user_api_tokens.is_active IS
    'True when the token is neither revoked nor expired';

-- SELECT only. Emphatically no UPDATE: this view exposes `scopes` and
-- `expires_at`, so an UPDATE grant would let a student widen their own token to
-- submissions:write or push its expiry out, defeating both the read-only
-- default and the four month bound. Revocation therefore goes through the
-- narrow RPC below, which can only ever set revoked_at.
-- (tests/db/student-update-row-counts.sql enforces that students hold UPDATE on
-- exactly one api view, and caught this.)
GRANT SELECT ON api.user_api_tokens TO student, ta, faculty;

-- ---------------------------------------------------------------------------
-- Revoking a token
-- ---------------------------------------------------------------------------
-- The one mutation a person may perform on their own token, and it is one-way.
-- Faculty may revoke anyone's, because a leaked credential must be killable
-- without the student being reachable.
CREATE FUNCTION api.revoke_user_api_token(p_id INT)
RETURNS TABLE (id INT, token_prefix TEXT, revoked_at TIMESTAMP WITH TIME ZONE)
SECURITY DEFINER
LANGUAGE plpgsql
SET search_path = pg_catalog, api, data, request, pg_temp
AS $$
DECLARE
    caller_id INT;
    caller_role TEXT;
BEGIN
    caller_id := request.user_id();
    caller_role := request.user_role();
    IF caller_id IS NULL THEN
        RAISE insufficient_privilege
            USING MESSAGE = 'a signed-in user is required to revoke an API token';
    END IF;

    -- Already-revoked tokens keep their original revoked_at: revocation is a
    -- fact about when access ended, and re-revoking must not move it.
    RETURN QUERY
    UPDATE data.user_api_token t
       SET revoked_at = coalesce(t.revoked_at, current_timestamp)
     WHERE t.id = p_id
       AND (caller_role = 'faculty' OR t.user_id = caller_id)
    RETURNING t.id, t.token_prefix, t.revoked_at;
END;
$$;

ALTER FUNCTION api.revoke_user_api_token(INT) OWNER TO yelukerest_migrator;
REVOKE ALL PRIVILEGES ON FUNCTION api.revoke_user_api_token(INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.revoke_user_api_token(INT) TO student, ta, faculty;

COMMENT ON FUNCTION api.revoke_user_api_token(INT) IS
    'Revoke one of the caller''s own API tokens (faculty may revoke any). One-way; cannot widen scopes or extend expiry.';

-- ---------------------------------------------------------------------------
-- Creating a token
-- ---------------------------------------------------------------------------
-- Called with the caller's own JWT, not a service credential: this is a person
-- acting on their own account, so PostgREST plus row-level security is the
-- whole authorization story and authapp need not be involved. That is why
-- create/list/revoke need no new HTTP surface -- only the exchange does,
-- because only the exchange is presented by an unauthenticated caller.
--
-- The secret is returned exactly once. There is no way to read it again.
CREATE FUNCTION api.create_user_api_token(
    p_name TEXT,
    p_scopes TEXT[] DEFAULT ARRAY['course:read', 'grades:read', 'submissions:read']::TEXT[],
    p_expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
) RETURNS TABLE (id INT, token TEXT, token_prefix TEXT, name TEXT, scopes TEXT[], expires_at TIMESTAMP WITH TIME ZONE)
SECURITY DEFINER
LANGUAGE plpgsql
SET search_path = pg_catalog, api, auth, data, request, settings, public, pg_temp
AS $$
DECLARE
    caller_id INT;
    new_prefix TEXT;
    new_secret TEXT;
    new_expires TIMESTAMP WITH TIME ZONE;
    new_id INT;
BEGIN
    caller_id := request.user_id();
    IF caller_id IS NULL THEN
        RAISE insufficient_privilege
            USING MESSAGE = 'a signed-in user is required to create an API token';
    END IF;

    IF p_name IS NULL OR char_length(trim(p_name)) = 0 OR char_length(p_name) > 100 THEN
        RAISE EXCEPTION 'a token name of 1 to 100 characters is required' USING ERRCODE = '22023';
    END IF;

    -- Default is read-only. submissions:write has to be asked for, matching the
    -- MCP consent page where the write scope starts unchecked.
    IF p_scopes IS NULL OR cardinality(p_scopes) = 0 THEN
        RAISE EXCEPTION 'at least one scope is required' USING ERRCODE = '22023';
    END IF;

    -- Four months by default: comfortably longer than a semester, so this is
    -- set up once and not thought about again. Length is not the control here;
    -- revocability is.
    new_expires := coalesce(p_expires_at, current_timestamp + interval '4 months');
    IF new_expires <= current_timestamp THEN
        RAISE EXCEPTION 'expires_at must be in the future' USING ERRCODE = '22023';
    END IF;

    -- 4 bytes of prefix for identification, 32 bytes of secret for entropy.
    new_prefix := 'yk_' || encode(public.gen_random_bytes(4), 'hex');
    new_secret := encode(public.gen_random_bytes(32), 'hex');

    INSERT INTO data.user_api_token (user_id, token_prefix, token_hash, name, scopes, expires_at)
    VALUES (caller_id, new_prefix, sha256(new_secret::bytea), trim(p_name), p_scopes, new_expires)
    RETURNING data.user_api_token.id INTO new_id;

    RETURN QUERY SELECT
        new_id,
        new_prefix || '_' || new_secret,
        new_prefix,
        trim(p_name),
        p_scopes,
        new_expires;
END;
$$;

ALTER FUNCTION api.create_user_api_token(TEXT, TEXT[], TIMESTAMP WITH TIME ZONE)
    OWNER TO yelukerest_migrator;
REVOKE ALL PRIVILEGES ON FUNCTION api.create_user_api_token(TEXT, TEXT[], TIMESTAMP WITH TIME ZONE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.create_user_api_token(TEXT, TEXT[], TIMESTAMP WITH TIME ZONE)
    TO student, ta, faculty;

COMMENT ON FUNCTION api.create_user_api_token(TEXT, TEXT[], TIMESTAMP WITH TIME ZONE) IS
    'Create a personal access token for the calling user. Returns the secret exactly once; read-only scopes by default, four month expiry.';

-- ---------------------------------------------------------------------------
-- Signing
-- ---------------------------------------------------------------------------
-- auth.sign_jwt is the browser path: right audience and lifetime, but carries
-- no scopes. auth.sign_mcp_user_jwt carries scopes but mints a ten-minute
-- token with a dual PostgREST+MCP audience, because that token is presented to
-- mcpapp as well. A token exchanged from a personal access token goes only to
-- PostgREST, so it needs the single audience and the ordinary lifetime, plus
-- scopes. Hence a third signer rather than bending either of the first two.
CREATE FUNCTION auth.sign_user_jwt_with_scopes(
    user_id INT,
    "role" data.user_role,
    netid TEXT,
    scopes TEXT,
    jti TEXT
) RETURNS TEXT
VOLATILE
SECURITY DEFINER
LANGUAGE sql
SET search_path = pg_catalog, auth, settings, pgjwt, pg_temp
RETURN pgjwt.sign(
    json_build_object(
        'iss', settings.get('jwt_issuer'),
        'aud', settings.get('jwt_audience'),
        'sub', 'user:' || user_id::text,
        'user_id', user_id,
        'role', "role"::TEXT,
        'netid', netid,
        'scopes', scopes,
        'iat', extract(epoch from now())::integer,
        'nbf', extract(epoch from now())::integer,
        'jti', jti,
        'exp', extract(epoch from now())::integer + settings.get('jwt_lifetime')::int
    ),
    settings.get('jwt_secret'));

ALTER FUNCTION auth.sign_user_jwt_with_scopes(INT, data.user_role, TEXT, TEXT, TEXT)
    OWNER TO yelukerest_migrator;
REVOKE ALL PRIVILEGES ON FUNCTION auth.sign_user_jwt_with_scopes(INT, data.user_role, TEXT, TEXT, TEXT) FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Exchanging a token for a JWT
-- ---------------------------------------------------------------------------
-- Admits only authapp's service credential, for the same reason
-- api.issue_user_jwt_for_mcp admits only mcpapp: the caller is a service
-- handing us a credential presented by someone not yet authenticated.
--
-- Every refusal returns an empty result rather than a distinguishable error.
-- An unknown prefix, a wrong secret, a revoked token and an expired token must
-- look identical from outside, or the endpoint becomes an oracle for which
-- prefixes exist.
--
-- On comparing hashes with `=`: the stored value is a SHA-256 of a 256-bit
-- random secret. A timing signal on digest comparison would only help an
-- attacker who can already choose the digest, which requires the secret. There
-- is no practical forgery path here, so a constant-time comparison would add
-- ceremony without adding safety.
CREATE FUNCTION api.exchange_user_api_token(p_token TEXT)
RETURNS TABLE (jwt TEXT, user_id INT, netid TEXT, "role" TEXT, scopes TEXT[])
SECURITY DEFINER
LANGUAGE plpgsql
SET search_path = pg_catalog, api, auth, data, request, settings, public, pg_temp
AS $$
DECLARE
    presented_prefix TEXT;
    presented_secret TEXT;
    token_row data.user_api_token%ROWTYPE;
    target_user data."user"%ROWTYPE;
    token_jti TEXT;
    signed_jwt TEXT;
BEGIN
    IF NOT (request.user_role() = 'app' AND request.app_name() = 'authapp') THEN
        RAISE insufficient_privilege
            USING MESSAGE = 'only the authapp service may exchange API tokens';
    END IF;

    -- Shape: yk_<8 hex>_<64 hex>. Anything else is not a token we issued.
    IF p_token IS NULL OR p_token !~ '^yk_[0-9a-f]{8}_[0-9a-f]{64}$' THEN
        RETURN;
    END IF;

    presented_prefix := substring(p_token from 1 for 11);
    presented_secret := substring(p_token from 13);

    SELECT t.* INTO token_row
    FROM data.user_api_token t
    WHERE t.token_prefix = presented_prefix
      AND t.token_hash = sha256(presented_secret::bytea)
      AND t.revoked_at IS NULL
      AND t.expires_at > current_timestamp;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    SELECT u.* INTO target_user FROM data."user" u WHERE u.id = token_row.user_id;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    token_jti := public.gen_random_uuid()::text;
    signed_jwt := auth.sign_user_jwt_with_scopes(
        target_user.id,
        target_user.role,
        target_user.netid,
        array_to_string(token_row.scopes, ' '),
        token_jti
    );

    UPDATE data.user_api_token
       SET last_used_at = current_timestamp
     WHERE data.user_api_token.id = token_row.id;

    RETURN QUERY SELECT
        signed_jwt,
        target_user.id,
        target_user.netid,
        target_user.role::text,
        token_row.scopes;
END;
$$;

ALTER FUNCTION api.exchange_user_api_token(TEXT) OWNER TO yelukerest_migrator;
REVOKE ALL PRIVILEGES ON FUNCTION api.exchange_user_api_token(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.exchange_user_api_token(TEXT) TO app;

COMMENT ON FUNCTION api.exchange_user_api_token(TEXT) IS
    'Exchange a personal access token for a short-lived scoped JWT. authapp only; every refusal is indistinguishable.';

-- ---------------------------------------------------------------------------
-- Compatibility
-- ---------------------------------------------------------------------------
-- Shape 7: api.user_api_tokens and two RPCs added. Set membership, not a floor
-- -- see docs/platform-compatibility.md.
CREATE OR REPLACE VIEW api.platform_version AS
    SELECT
        'yelukerest'::text AS platform,
        1::integer AS platform_compatibility_version,
        7::integer AS schema_compatibility_version,
        10::integer AS admin_api_version;

ALTER VIEW api.platform_version OWNER TO api;

NOTIFY pgrst, 'reload schema';
