-- Revert yelukerest:init from pg

BEGIN;

DROP SCHEMA api CASCADE;
DROP SCHEMA auth CASCADE;
DROP SCHEMA "data" CASCADE;
DROP SCHEMA pgjwt CASCADE;
DROP SCHEMA rabbitmq CASCADE;
DROP SCHEMA request CASCADE;
DROP SCHEMA settings CASCADE;
DROP EXTENSION IF EXISTS plpgsql;
DROP EXTENSION IF EXISTS pgcrypto;

COMMIT;
